### PR TITLE
Fix the current onboarding step being returned as shipping even after saving rates

### PR DESCRIPTION
**Pull request by nima-karimi**
### Changes proposed in this Pull Request:

The API to return the current onboarding step (`GET wc/gla/mc/setup`) did not recognize the newly added `automatic` mode for syncing shipping settings and also the query to count the countries that have a saved shipping rate was not working as expected. This PR fixes these issues.

### Detailed test instructions:

It's easier to test this with the UI parts in, so you can first checkout Gan's PR #1267 branch `feature/shipping-rates-ui/setup-mc` and build all the JS files to have it cached then go back to this branch and test the backend implementation. Once you have all the JS files from Gan's branch:

1. Remove all current MC settings from your DB to have a fresh onboarding
2. Go through onboarding, choose a few target audience countries, and at the shipping step, choose the "Recommended: Automatically sync my store’s shipping settings to Google." option
3. Go to the next step and then refresh the page
4. Confirm you're redirected to the store requirements page instead of the shipping
5. Go back to the shipping step and this time choose "My shipping settings are simple. I can manually estimate flat shipping rates."
6. Enter the shipping rates manually for all selected target audience countries
7. Go to the next step and then refresh the page
8. Confirm you're redirected to the store requirements page instead of the shipping

### Changelog entry

>

### CODE REVIEW

**Comment by eason9487** [comment]
It works well on my local end. 💯 

https://user-images.githubusercontent.com/17420811/157218921-d7c89f44-f5de-45e3-ab75-294b54dd5212.mp4

I only checked the runtime result on the frontend side because I can't evaluate the PHP code part. 🙏

**Comment by eason9487** [comment]
I locally cherry-picked this onto #1267 and tried a few different combinations of settings in step 3. Tthey all worked correctly. 👍

**Review by mikkamp — APPROVED** [review]
I tested the PHP code and I'm getting the result I expected when trying different combinations of shipping settings.

I was initially a bit confused why we add a second `array_diff` check, but I see now that's to ensure that the set of countries is actually the same and not just the count. We could add the same check for the shipping times if we wanted to be a bit stricter.

**Comment by nima-karimi** [comment]
> We could add the same check for the shipping times if we wanted to be a bit stricter.

Added this in https://github.com/woocommerce/google-listings-and-ads/pull/1298/commits/85db3c57106a2e8c09180d6e2f35e17ce6323913.

**Pull request merged**
