### PR TITLE
UX Improvement: Tweak Google Ads card layout

### PR DESCRIPTION
**Pull request by ecgan**
### Changes proposed in this Pull Request:

Based on PR https://github.com/woocommerce/google-listings-and-ads/pull/1113.

This PR slightly tweaks the layout for the `ConnectAds` card in Setup Ads, so that the UI is more consistent with other cards in the Setup MC flow. Specifically, we make the `AdsAccountSelectControl` grow to full width and make the gap between the SelectControl and the Connect button smaller.

### Screenshots:

Before:

image

After:

image

### Detailed test instructions:

Pre-requisite: Your Google account should have existing Google Ads account. If you do not have a Google Ads account, you can go through the Setup Ads flow and create a new Google Ads account first, and then disconnect the Google Ads account (in the plugin settings page or the connection test page), and then go through the Setup Ads flow again.

1. Go to Setup Ads.
2. The Google Ads account card should look like above.

### Changelog entry

> Tweak - Minor layout tweak in Google Ads card in Setup Ads.

### CODE REVIEW

**Comment by eason9487** [comment]
I saw @puntope added a 👀  on this PR. Probably he has started the review.

Sorry I'd like to chip in an alternative idea. 🙏
Using the `gap` prop of `<Flex>` and `<FlexBlock>` provided by `@wordpress/components` could omit the style adjustments.

```js
<Flex gap={ 3 }>
	<FlexBlock>
		<AdsAccountSelectControl
			value={ value }
			onChange={ setValue }
		/>
	</FlexBlock>
	{ /* ...omitted */ }
```

**Comment by puntope** [comment]
> I saw @puntope added a 👀 on this PR. Probably he has started the review.

Yes, I was on it in order to get familiar also with components. But definitely better to use 6 eyes instead of 4 :)

**Comment by ecgan** [comment]
@eason9487 ,

> Using the `gap` prop of `<Flex>` and `<FlexBlock>` provided by `@wordpress/components` could omit the style adjustments.

Yes, I thought about the `gap` prop. However, I wanted to make it consistent and similar to all the other cards in Setup MC. We are using `ContentButtonLayout`, and the gap specified in `ContentButtonLayout` CSS is responsive based on the viewport. For example, when we are in a smaller screen, the gap would be only 8px (shown in the screenshot below), while in a larger desktop screen, the gap would be 12px.

image

**Comment by eason9487** [comment]
@ecgan,

> I wanted to make it consistent and similar to all the other cards in Setup MC. We are using `ContentButtonLayout`, and the gap specified in `ContentButtonLayout` CSS is responsive based on the viewport.

Thanks for the reply. I got your point.

**Comment by puntope** [comment]
> The Google Ads account card should look like above.

This is what I see in setup-ads page

Screenshot 2021-11-26 at 14 52 16
Screenshot 2021-11-26 at 14 53 34

**Comment by ecgan** [comment]
@puntope , 

> This is what I see in setup-ads page

You are seeing that because your Google account did not have an existing Google Ads account. I should have mentioned that in the test instructions, sorry about that. 😅  I have added that info in the test instruction in the PR description above. You would need to disconnect your Google Ads account and then go through the Setup Ads flow, then you will see the `ConnectAds` card.

**Review by puntope — APPROVED** [review]
✅  Looks good!

What I thought tested?

Check if the appearance is like the one mentioned in that he PR 👌 
Check if in < 783px viewport GAP is 8px 👌 
Check if in >= 783px viewport GAP is 12px 👌

**Pull request merged**
