### PR TITLE
Shipping Integration - Syncing rates for states/provinces and postal codes

### LINKED ISSUE #1228: WooCommerce Shipping Zones Integration - Syncing rates for states/provinces and postal codes
## Objective
The aim is to provide integration with WooCommerce shipping zones so that the shipping rates are set for various regions such as states, provinces, and postal/zip codes can be automatically synchronized with Google Merchant Center.

## Overview
In this milestone, we will set up the system required to automatically map the supported shipping methods defined for each state/province or zip code in all WooCommerce shipping zones into their respective Merchant Center settings.

## The current state of the system
At the end of milestone one, we currently have an integration with WooCommerce shipping zones. However, it only works at a country level. Meaning that the shipping methods are all grouped together and synchronized for each country. Even if they are defined at a more granular level such as a state or zip code.

Currently, the user has three options when it comes to setting their store’s shipping settings during the onboarding process:

> - Recommended: Automatically sync my store’s shipping settings to Google.
> - My shipping settings are simple. I can manually estimate flat shipping rates.
> - My shipping settings are complex. I will enter my shipping rates manually in Google Merchant Center

image
Three options are presented to users for setting the shipping rates during onboarding.

The automatic syncing will happen only if the user chooses the first option. In that case, we map each shipping method defined in WooCommerce shipping zones to a Merchant Center shipping service.

## WooCommerce Shipping Zones
A Shipping Zone is a geographical area to which you ship items. You can get as specific as you need, right down to regions and zip codes, or you can leave it more general. Each customer matches only one zone.

To set up shipping in WooCommerce, you first set up shipping zones, then add methods to those zones, and lastly, rates to your methods. You can create as many zones as you like, and add multiple methods and rates to each zone.

image
Defining a shipping zone

Each zone can have multiple regions along with multiple postcodes associated with it. The regions can be defined as continents, countries, or states and provinces of each country. The postcodes can also be defined either as ranges (90301-90305), wildcards (9003*), or one number (90210).

WooCommerce supports the state/province level for many countries. The list is provided as a PHP file called [states.php](https://github.com/woocommerce/woocommerce/blob/9d08ac8ac3723c897e08ac2ff8a6d950f0e26b5b/plugins/woocommerce/i18n/states.php) on WooCommerce source code.

There are also several countries where WooCommerce doesn’t provide the options for their states/provinces. Germany and Netherlands, for example, can only be defined as a country level in WooCommerce shipping zones.

## Merchant Center Account-level Shipping Settings

Each Merchant Center account can have one and only one ShippingSettings associated with it, which defines an array of shipping services, warehouses, and postal code groups for that account:

property | type | description
-- | -- | --
**`accountId`** | string | The ID of the account to which these account shipping settings belong. Ignored upon update, always present in get request responses.
**`services[]`** | [Service](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#Service) | The target account's list of services. Optional.
**`postalCodeGroups[]`** | [PostalCodeGroup](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#PostalCodeGroup) | A list of postal code groups that can be referred to in services. Optional.
`warehouses[]` | [Warehouse](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#Warehouse) | Optional. A list of warehouses that can be referred to in services.

All postal codes that we plan to refer to in our shipping service should be defined in the postalCodeGroups property beforehand. The [PostalCodeGroup](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#PostalCodeRange) class has the following properties:

property | type | description
-- | -- | --
**`name`** | string | The name of the postal code group referred to in headers. Required.
**`country`** | string | The CLDR territory code of the country the postal code group applies to. Required.
**`postalCodeRanges[]`** | [PostalCodeRange](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#PostalCodeRange) | A range of postal codes. Required.

The `postalCodeRanges` accepts an array of [PostalCodeRange](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#PostalCodeRange) objects, each with the following properties:

property | type | description
-- | -- | --
**`postalCodeRangeBegin`** | string | A postal code or a pattern of the form prefix* denoting the inclusive lower bound of the range defining the area. Examples values: "94108", "9410*", "9*". Required.
**`postalCodeRangeEnd`** | string | A postal code or a pattern of the form prefix* denoting the inclusive upper bound of the range defining the area. It must have the same length as postalCodeRangeBegin: if postalCodeRangeBegin is a postal code then postalCodeRangeEnd must be a postal code too; if postalCodeRangeBegin is a pattern then postalCodeRangeEnd must be a pattern with the same prefix length. Optional: if not set, then the area is defined as being all the postal codes matching postalCodeRangeBegin.

Each shipping [Service](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#Service) defined for a Merchant Center account has the following properties:

property | type | description
-- | -- | --
**`name`** | string | Free-form name of the service. Must be unique within the target account. Required.
**`deliveryCountry`** | string | The CLDR territory code of the country to which the service applies. Required.
**`currency`** | string | The CLDR code of the currency to which this service applies. Must match that of the prices in rate groups.
`deliveryTime` | [DeliveryTime](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#DeliveryTime) | Time spent in various aspects from order to the delivery of the product. Required.
**`rateGroups[]`** | [RateGroup](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#RateGroup) | Shipping rate group definitions. Only the last one is allowed to have an empty applicableShippingLabels, which means "everything else". The other applicableShippingLabels must not overlap.
**`active`** | boolean | A boolean exposing the active status of the shipping service. Required.
**`minimumOrderValue`** | [Price](https://developers.google.com/shopping-content/reference/rest/v2.1/Price) | Minimum order value for this service. If set indicates that customers will have to spend at least this amount. All prices within a service must have the same currency. Cannot be set together with minimumOrderValueTable.
`eligibility` | string | Eligibility for this service.Acceptable values are:"All scenarios""All scenarios except Shopping Actions""Shopping Actions"
**`shipmentType`** | string | Type of locations this service ships orders to.Acceptable values are:"delivery""pickup"
`pickupService` | [PickupCarrierService](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#PickupCarrierService) | The carrier-service pair delivering items to collection points. The list of supported pickup services can be retrieved via the getSupportedPickupServices method. Required if and only if the service delivery type is pickup.
`minimumOrderValueTable` | [MinimumOrderValueTable](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#MinimumOrderValueTable) | Table of per store minimum order values for the pickup fulfillment type. Cannot be set together with minimumOrderValue.

The `rateGroup` item is defined as an array of [RateGroup](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#RateGroup) objects each with the following properties:

property | type | description
-- | -- | --
**`applicableShippingLabels[]`** | string | A list of shipping labels defining the products to which this rate group applies to. This is a disjunction: only one of the labels has to match for the rate group to apply. May only be empty for the last rate group of a service. Required.
**`singleValue`** | [Value](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#Value) | The value of the rate group (e.g. flat rate $10). Can only be set if mainTable and subtables are not set.
**`mainTable`** | [Table](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#Table) | A table defining the rate group, when singleValue is not expressive enough. Can only be set if singleValue is not set.
`subtables[]` | [Table](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#Table) | A list of subtables referred to by mainTable. Can only be set if mainTable is set.
`carrierRates[]` | [CarrierRate](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#CarrierRate) | A list of carrier rates that can be referred to by mainTable or singleValue.
**`name`** | string | Name of the rate group. Optional. If set has to be unique within shipping service.

Each `rateGroup` can either have a `signleValue` defined as its rate OR a table of rates (using `mainTable` and `subtables`). To define the shipping rates for different regions/states/provinces and postal/zip codes we need to make use of the `mainTable` property, which accepts an instance of the [Table](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#Table) class with various rows and columns.

A rate table can have a list of rows (instances of [Row](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#Row) class), each containing a list of [Value](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#Value) objects, and the following headers (instance of [Headers](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#Headers) class) defined as either `rowHeaders` (if the table has only one dimension) or `columnHeaders` (if the table has more than one dimension):

property | type | description
-- | -- | --
`prices[]` | [Price](https://developers.google.com/shopping-content/reference/rest/v2.1/Price) | A list of inclusive order price upper bounds. The last price's value can be "infinity". For example [{"value": "10", "currency": "USD"}, {"value": "500", "currency": "USD"}, {"value": "infinity", "currency": "USD"}] represents the headers "<= $10", "<= $500", and "> $500". All prices within a service must have the same currency. Must be non-empty. Can only be set if all other fields are not set.
`weights[]` | [Weight](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#Weight) | A list of inclusive order weight upper bounds. The last weight's value can be "infinity". For example [{"value": "10", "unit": "kg"}, {"value": "50", "unit": "kg"}, {"value": "infinity", "unit": "kg"}] represents the headers "<= 10kg", "<= 50kg", and "> 50kg". All weights within a service must have the same unit. Must be non-empty. Can only be set if all other fields are not set.
`numberOfItems[]` | string | A list of inclusive number of items upper bounds. The last value can be "infinity". For example ["10", "50", "infinity"] represents the headers "<= 10 items", "<= 50 items", and "> 50 items". Must be non-empty. Can only be set if all other fields are not set.
**`postalCodeGroupNames[]`** | string | A list of postal group names. The last value can be "all other locations". Example: ["zone 1", "zone 2", "all other locations"]. The referred postal code groups must match the delivery country of the service. Must be non-empty. Can only be set if all other fields are not set.
**`locations[]`** | [LocationIdSet](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#LocationIdSet) | A list of location ID sets. Must be non-empty. Can only be set if all other fields are not set.

In this milestone, we will only deal with the `postalCodeGroupNames` and the `locations` properties.

The [LocationIdSet](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#LocationIdSet) object accepts a list of `locationIds` as its only property. All location IDs in this list must be of the same type (state, etc.).

The location IDs are defined by Google in a [downloadable CSV file](https://developers.google.com/adwords/api/docs/appendix/geotargeting) on the AdWords API documentation. Note that this file is regularly updated. 

It’s important to note that only one of the [Headers](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#Headers) properties can be set for one object. Meaning that each [Headers](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#Headers) object can’t have multiple properties.

## Mapping WooCommerce shipping zones to Google shipping settings

Each WooCommerce shipping zone can contain multiple regions (states/provinces and countries) and multiple shipping methods and rates.

Each region can be any of the following:

- A country
- A state/province
- A continent (Europe, America, Asia, etc.)

Additionally, each shipping zone can have multiple postcodes, postcode patterns, or ranges of postcodes associated with it. If a postcode is defined for a zone, then it will only apply to the orders shipping to that postcode, even if the country or state is a match.

Moreover, each region can be defined in multiple zones at the same time and have different methods. To be able to map them to a Merchant Center Shipping Service, we first need to go through all shipping zones and group all of the defined shipping methods for each region. Note that the postcodes defined in each zone should be also considered when grouping the methods.

We currently aim to sync only the flat-rate and free-shipping options; therefore, any other shipping methods including the local-pickup option can be ignored.

### Possible states of shipping rates definitions in shipping zones

We can have the following states for the flat-rate shipping method when going through the list of shipping options in WooCommerce shipping zones:

#### The same rate for one or multiple regions in the same shipping zone

In this case, we will copy the same rate and shipping options (class rates, etc.) for all of the regions, states/provinces, etc.
Multiple rates for the same region in the same zone or different zones

#### Multiple rates for the same region in the same zone or different zones

This case should be handled differently for flat-rate and free-shipping methods:

##### Flat-rate

If there are multiple rates set for the flat-rate shipping method in one or multiple zones, we need to use the maximum rate and send that over to Google.

##### Free-shipping

If multiple free-shipping methods are offered for the same region but with different settings for the minimum order value, we always set the minimum order value to the maximum amount.

### Difference between region granularity provided by WooCommerce and Merchant Center

As it was previously mentioned, WooCommerce supports setting the region as a state/province for a selected list of countries. This list is stored in a PHP file called [states.php](https://github.com/woocommerce/woocommerce/blob/9d08ac8ac3723c897e08ac2ff8a6d950f0e26b5b/plugins/woocommerce/i18n/states.php) on WooCommerce source code.

Merchant Center, on the other hand, only offers state-level granularity for a handful of countries:

- **US**: postal code, state
- **AU**: postal code, territory
- **FR**: postal code, region
- **JP**: prefecture (shipping cost only)
- **All others**: country-level

For the four countries supported by the Merchant Center, we need to implement the state-level calculations and mapping. However, for all other countries, the shipping rates should still be calculated on a country level (as in milestone one).

### WooCommerce region ID vs. Merchant Center location ID

WooCommerce stores the regions using the [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) format as key and their translated name as the value in the [states.php](https://github.com/woocommerce/woocommerce/blob/9d08ac8ac3723c897e08ac2ff8a6d950f0e26b5b/plugins/woocommerce/i18n/states.php) file, whereas Google stores their name, ID, and country-code in the provided [CSV file](https://developers.google.com/adwords/api/docs/appendix/geotargeting). Google API requires each location’s respective ID in the `locationIds` property when submitting the shipping settings. WooCommerce, for example, has the following entry for the United States:

```PHP
'US' => array( // United States.
        'AL' => __( 'Alabama', 'woocommerce' ),
        'AK' => __( 'Alaska', 'woocommerce' ),
        'AZ' => __( 'Arizona', 'woocommerce' ),
        'AR' => __( 'Arkansas', 'woocommerce' ),
        'CA' => __( 'California', 'woocommerce' ),
        'CO' => __( 'Colorado', 'woocommerce' ),
        // …
```

Google, on the other hand, provides the following entries for the same country:

Criteria ID | Name | Canonical Name | Parent ID | Country Code | Target Type | Status
-- | -- | -- | -- | -- | -- | --
21132 | Alaska | Alaska,United States | 2840 | US | State | Active
21133 | Alabama | Alabama,United States | 2840 | US | State | Active
21135 | Arkansas | Arkansas,United States | 2840 | US | State | Active
21136 | Arizona | Arizona,United States | 2840 | US | State | Active
21137 | California | California,United States | 2840 | US | State | Active
21138 | Colorado | Colorado,United States | 2840 | US | State | Active

Since Google doesn’t use the ISO 3166-2 format for the region names in their provided CSV file, we need to map them to WooCommerce regions using their full English name. This means that if we were to use the CSV file directly in order to query the Google table and get the location ID of a state such as Alaska, we would need to search in the name column for the state’s English name (while also filtering based on country code and target type).

Given that the number of countries supported on a state, province, etc. level by Merchant Center is low, we can manually go through the CSV file and map each of them to their respective WooCommerce region IDs (in [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2)).

We then need to store the mappings in our codebase so that we can access the location ID for each state, province, prefecture, or territory on-demand.

### LINKED ISSUE #1230: Shipping Integration - Map rates for provinces/states and postal codes
As part of #1228

This issue is dependent on #1229.

At the end of milestone one, we currently have an integration with WooCommerce shipping zones. However, it only works at a country level. Meaning that the shipping methods are all grouped together and synchronized for each country. Even if they are defined at a more granular level such as a state or zip code.

Each WooCommerce shipping zone can have multiple regions along with multiple postcodes associated with it. The regions can be defined as continents, countries, or states and provinces of each country. The postcodes can also be defined either as ranges (90301-90305), wildcards (9003*), or one number (90210).

Even though WooCommerce supports the state/province level for many countries (see [states.php](https://github.com/woocommerce/woocommerce/blob/9d08ac8ac3723c897e08ac2ff8a6d950f0e26b5b/plugins/woocommerce/i18n/states.php)), Merchant Center only supports state-level granularity for a handful of countries. The list of supported countries along with their subregions should be provided by the helper methods implemented in #1229.

The `ShippingZone` class handles the processing of WooCommerce shipping zones and groups their methods and rates by country.

Modify the `parse_shipping_zones` method so that it stores the list of methods for each supported region separately. This means that we first need to check if the zone’s country is one of the ones supported by Merchant Center on a more granular level and then instead of grouping the shipping methods by country, we group them by the state, province, etc.

The postcodes stored in each zone should also be taken into account. If a zone has postcodes associated with it then all of its methods only apply to those postcodes, even if its region is on the country level.

The `get_shipping_rates_for_country` method should be modified to return the shipping rates for each region down to the postcode granularity. The returned rates can still be grouped by country. A new property can be added to the returned response containing the rates for each sub-region within that country (if supported by Merchant Center).

For more details on the mapping check #1228.

### LINKED ISSUE #1231: Shipping Integration - Syncing the rates for provinces/states and postal codes
As part of #1228

This issue is dependent on #1230.

Once we have the rates for supported subregions of shipping countries, we can submit them to Merchant Center by modifying the `API/Google/Settings` class.

The rates for sub-regions and postcodes will be submitted only if the user has chosen the “automatic” shipping option during onboarding.

The `update_shipping_rates` method and other related methods will be modified to take into account the new property returned by the `ShippingZone::get_shipping_rates_for_country` method. This property includes the list of shipping rates for each subregion (state, province, postcode, etc.).

The list of returned postcodes should be provided as an array of [PostalCodeGroup](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#PostalCodeGroup) objects under the postalCodeGroups property of [ShippingSettings](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#resource:-shippingsettings). This will allow us to refer to it in our shipping rates table.

Currently, to store the rates, we create one [RateGroup](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#RateGroup) as the main flat rate and then optionally multiple other [RateGroup](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#RateGroup) objects for different shipping classes/labels.

Submitting the rates for postcodes or subregions is only possible by creating an instance of the [Table](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#Table) class and filling it with [Headers](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#Headers) and [Rows](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#Row). The [RateGroup](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#RateGroup) has a `mainTable` property that accepts an instance of the [Table](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#Table) class.

For example, if WooCommerce has the following shipping zones and methods:

Zone name | Region | Shipping methods
-- | -- | --
Local | California ZIP 90210 | Flat rate ($10)
State | California | Flat rate ($20

This will translate to the following table set in the [RateGroup](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#RateGroup) object:

locations/postalCodeGroupNames | 21137(California state location ID fetched from the Google CSV)
-- | --
90210 | $10
"all other locations" | $20

The "all other locations" string is a special string that can be used in the `postalCodeGroupNames` property to specify the rates for all other postcodes in the area.

A table can have two dimensions with two headers. It can have as many [Rows](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#Row) as the number of `rowHeaders`. Each [Row](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#Row) can contain as many cells as the number of `columnHeaders`.

In the example above, the `rowHeaders` object has the following values set for its `postalCodeGroupNames` property: 90210 and “all other locations”. Consequently, the `columnHeaders` property has the following value set for its `locations` property: 21137. The table `rows` property has an array of two [Row](https://developers.google.com/shopping-content/reference/rest/v2.1/shippingsettings#Row) objects each containing one cell with the shipping cost: $10 and $20.

### PR DESCRIPTION
**Pull request by nima-karimi**
### Changes proposed in this Pull Request:

Closes #1228.
Closes #1230.
Closes #1231.

This is the main feature branch for the shipping integration milestone two. All of the work in this PR has already been reviewed, tested, and merged from other PRs:

- https://github.com/woocommerce/google-listings-and-ads/pull/1341
- https://github.com/woocommerce/google-listings-and-ads/pull/1422
- https://github.com/woocommerce/google-listings-and-ads/pull/1455
- https://github.com/woocommerce/google-listings-and-ads/pull/1445
- https://github.com/woocommerce/google-listings-and-ads/pull/1560
- https://github.com/woocommerce/google-listings-and-ads/pull/1574

### Changelog entry

> Add - Option to automatically sync the shipping rates based on the store shipping zone configurations

### CODE REVIEW

**Comment by nima-karimi** [comment]
@ecgan Just FYI. Let me know if you're ok with this PR being merged to develop. I think your PR for removing the shipping method (#1445) is pointing to `develop` so there shouldn't be any dependencies to this one.

**Comment by ecgan** [comment]
@nima-karimi , thanks for the ping. 🙂 

> I think your PR for removing the shipping method (#1445) is pointing to `develop` so there shouldn't be any dependencies to this one.

PR #1445 currently sits on top of PR #1410. When #1410 is merged into `develop`, I want to do some merging and rebase so that in the end #1445 will be merged into this PR #1494 of yours here, i.e. PR #1445 should be released together with your backend API changes.

If we were to merge this #1494 into `develop` without #1445 in it, I think the front-end side would break.

**Comment by ecgan** [comment]
@nima-karimi , there was a merge conflict in `src/Internal/DependencyManagement/CoreServiceProvider.php` file, I fixed it in the commit [`d6b2d96` (#1494)](https://github.com/woocommerce/google-listings-and-ads/pull/1494/commits/d6b2d96147c9866adb33c7cd35f9ef9f0820ac6f), could you double check and see if it is okay?

If you click on the commit link above, click on the "view full changes", and look for the file, you will see the changes the commit made in this feature branch, see screenshot below:

image

The above changes come from PR https://github.com/woocommerce/google-listings-and-ads/pull/1502.

**Comment by nima-karimi** [comment]
Thanks @ecgan, Merge looks good to me! Was `CoreServiceProvider.php` the only file that had a merge conflict?

**Comment by ecgan** [comment]
> Was `CoreServiceProvider.php` the only file that had a merge conflict?

@nima-karimi , yes, it was the only file that had a merge conflict. 🙂 

For this kind of merge conflict commit, usually I would have a list of conflicted files in the commit message, e.g. see screenshot below for the merge conflict commit [`d6b2d96` (#1494)](https://github.com/woocommerce/google-listings-and-ads/pull/1494/commits/d6b2d96147c9866adb33c7cd35f9ef9f0820ac6f). So from there, we know there was only one file having conflict:

image

**Comment by nima-karimi** [comment]
Great. Then I guess everything looks good.

**Pull request merged**
