### PR TITLE
Update Plugin Icons

### LINKED ISSUE #1644: Change Google-related logos to the generic G logo
### Describe the bug:
The Googlers have flagged to us that we should use the generic G logo rather than the Shopping tag logo or the Ads logo. 
We need to change the [wordpress.org plugin page](https://wordpress.org/plugins/google-listings-and-ads/) to the G logo. 

We should also double check our plugin to ensure there are no other Google-related logos anywhere.

### Generic G logo:
Download assets here: https://www.dropbox.com/sh/jiorzn7k2tk01gt/AAC_VevHZhbOHK3YG_iZkhBJa?dl=0

### PR DESCRIPTION
**Pull request by puntope**
### Changes proposed in this Pull Request:

Closes #1644  

Replace old google Shopping icons with the new ones with the G letter logo

### Screenshots

Screenshot 2022-08-25 at 18 27 59

Screenshot 2022-08-25 at 18 28 04

### Detailed test instructions:

- Check the new images in `wordpress_org_assets`
- Check the image icon.svg - 128x128 and with white background
- Check the image icon-no-bg.svg -  128x128 and with NO background
- Check the image icon128x128.png - 128x128 and with white background
- Check the image icon256x256.png - 256x256 and with white background
- Check that there is no icons in the code referring to the old icons 

### Changelog entry

>  Tweak - Updated plugin icons

### CODE REVIEW

**Review by mikkamp — APPROVED** [review]
The icon changes look good to me. Just wanted to mention that they need to be manually committed to svn, as that's not something WR will handle, nor are they tied to a specific version.

So you'll need to commit them to this folder: https://plugins.svn.wordpress.org/google-listings-and-ads/assets/

See details here: https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/

**Comment by puntope** [comment]
> So you'll need to commit them to this folder: https://plugins.svn.wordpress.org/google-listings-and-ads/assets/

How can I commit that manually ? Is there a command?

In the docs you send me I dont see it

**Comment by puntope** [comment]
I found this... probably is what Im lokking for... I will investigate further tomorrow

https://svnbook.red-bean.com/en/1.8/svn.ref.svn.c.commit.html

**Comment by mikkamp** [comment]
Yes you'll need to use some basic svn commands to checkout a copy and commit the changes (similar to how you would use git from the command line).

Here is an example of how I've done it in the past:
```
mkdir svn && cd svn
svn checkout https://plugins.svn.wordpress.org/google-listings-and-ads --depth immediates
cd google-listings-and-ads/assets && svn update --set-depth infinity .
-- Replace with new files here --
svn ci -m 'Updating assets'
```

You can run `svn status` to see what actually changed before running the commit (ci) command.

**Comment by puntope** [comment]
Interesting, thanks @mikkamp I will try it and add some docs to the wiki for the future

> -- Replace with new files here --

Can you elaborate how can I add here the files?

**Comment by puntope** [comment]
Never mind, I see it was just replace the files in the directory

**Pull request merged**
