### PR TITLE
Update travis config to use latest version of WP and WC

### PR DESCRIPTION
**Pull request by nima-karimi**
### Changes proposed in this Pull Request:

This PR updates the WooCommerce and WordPress versions in our Travis configurations to the latest versions we support.

### Detailed test instructions:

1. Check that Travis build runs successfully

### CODE REVIEW

**Review by tomalec — APPROVED** [review]
LGTM

**Review by mikkamp — COMMENTED** [review]
I was looking at these as well. But we currently only set the environment variables and don't do anything else with it. Probably useful for the e2e tests though.

Just noticed though that the JS and phpcs tests still have WC_VERSION set to master.

**Comment by nima-karimi** [comment]
I actually created this as part of my upcoming PR for unit tests. It'll be useful there 😅

**Comment by mikkamp** [comment]
Just a small nitpick but why not add a WC_LATEST variable and set that to trunk? Besides is it even reliable to test with trunk, shouldn't we test with release candidates?

**Comment by nima-karimi** [comment]
> Besides is it even reliable to test with trunk, shouldn't we test with release candidates?

It could make our tests a bit unstable but if we add a constant version, we would then need to keep updating this file every few weeks to keep up with the latest WooCommerce release. So it's kind of a trade-off.

Unless we do the check for the latest WooCommerce version in our script. WordPress has this API for it `https://api.wordpress.org/core/version-check/1.7/`, not sure if WooCommerce also has something similar.

**Pull request merged**
