### PR TITLE
Update WC tested version to 6.0 after testing

### PR DESCRIPTION
**Pull request by puntope**
### Changes proposed in this Pull Request:

Bumping WooCommerce tested up to version to 6.0  after compatibility testing.

### Smoke tests
- Onboarding completed, played randomly with the options and buttons to see it does what is expected.
- Seeing that the synchronisation started, showing me feedback in the dashboard
- Dashboard section shows and seems to work
- Reports section shows and seems to work
- Settings section shows and seems to work. Disconnected successfully my account. Change my phone etc
- No console errors/log errors so far

### CODE REVIEW

**Comment by tomalec** [comment]
I'd also update https://github.com/woocommerce/google-listings-and-ads/blob/develop/readme.txt#L66

**Comment by puntope** [comment]
> I'd also update https://github.com/woocommerce/google-listings-and-ads/blob/develop/readme.txt#L66

Good catch, was checking at the top, and I didn't see that one.

**Comment by tomalec** [comment]
To fully bump everything related to WC version to "at least 5.8", we should also bump and test DEWP-externalized Woo dependencies to the version used by WC 5.8 (-> [WC-admin `2.7.2`](https://github.com/woocommerce/woocommerce/blob/5.8.0/composer.json) -> [`@woocommerce/components` @ `8.1.0`](https://github.com/woocommerce/woocommerce-admin/blob/v2.7.2/packages/components/package.json#L3))

If you tested live instance with 5.8, you should (theoretically, and most probably) test it already. So what's left untested is our unit tests.

The script from https://github.com/woocommerce/google-listings-and-ads/pull/1107 could help you find those externalized deps:
image

**Comment by puntope** [comment]
> The script from #1107 could help you find those externalized deps:

I created a new branch from this one, merge there the branch with the script and run `npm run outdated:dewp` but I dont see anything related to  WC-admin 2.7.2. 

Unsure how to use the script

**Comment by puntope** [comment]
Secondly it comes to my mind if its recommended to bump all of those dependencies before WC/WP release. Thoughts?

**Comment by tomalec** [comment]
We don't have a process for bumping those dependencies. Before we were not updating them regularly. And I simply thought it may be a good idea to start.

So if you have problems finding those versions feel free to leave them for later.

> I created a new branch from this one, merge there the branch with the script and run npm run outdated:dewp but I dont see anything related to WC-admin 2.7.2.

Yep, unfortunately, we do not have a script yet, to give the versions used in WC. We need to track that manually:
> WC 5.8 (-> WC-admin 2.7.2 -> @woocommerce/components @ 8.1.0)

`npm run outdated:dewp` gives you only the list of externalized packages, that may have an updated (without a version, or guaranty that it actually needs to be bumped.

**Comment by tomalec** [comment]
> Secondly it comes to my mind if its recommended to bump all of those dependencies before WC/WP release. Thoughts?

Definitely a good point.
Maybe we should rather have a process like this (Given we try to stick to L-2 policy)
0. WC/WP beta is released
1. Do the compatibility checks
2. Bump tested up to versions
- here is the time we formally support L-3 = Latest beta and three lower minor releases (Lβ-3)
3. WC/WP is fully released
4. We start a separate cleanup process, bumping minimum supported WC/WP versions and their externalized dependencies.
5. We can also remove other legacies, compatibility, forked code, etc.

**Comment by puntope** [comment]
> Maybe we should rather have a process like this (Given we try to stick to L-2 policy)

I think that is the more accurate, since actually 6.0 and 5.9 are not live yet. So L-2 would be still 5.6 and 5.7. 

We are only indicating that we actually perform the testing over those new versions. 

I rolled back the minimum versions. Let me know if this is now ready for merge :)

**Pull request closed without merging**
