### PR TITLE
Update Google API Client to 2.15 and Google Ads API to V13

### PR DESCRIPTION
**Pull request by ianlin**
### Changes proposed in this Pull Request:

**Project**: pcTzPl-1w2-p2

This PR updates the Google Ads library from V12 > V13 as well as Google Content API (Merchant Centre) to 2.15.

- Update the Google Client services
- Update the Google Ads API from V12 to V13
- Change all imports from V12 > V13
- Cleanup older versions of the Ads library V10 - V12

### Updated packages
```
composer update googleads/google-ads-php --with-all-dependencies

- Upgrading firebase/php-jwt (v6.4.0 => v6.5.0)
- Upgrading google/auth (v1.26.0 => v1.28.0)
- Upgrading google/common-protos (v3.2.0 => v4.1.0)
- Upgrading google/gax (v1.19.0 => v1.20.2)
- Upgrading google/protobuf (v3.22.2 => v3.23.2)
- Upgrading googleads/google-ads-php (v17.1.0 => v19.1.0)
- Upgrading guzzlehttp/guzzle (v7.5.0 => 7.7.0)
- Upgrading guzzlehttp/promises (1.5.2 => 1.5.3)
- Upgrading guzzlehttp/psr7 (2.4.4 => 2.5.0)
- Upgrading psr/http-message (1.1 => 2.0)

composer update google/apiclient --with-all-dependencies

- Upgrading google/apiclient (v2.13.2 => v2.15.0)
- Upgrading google/apiclient-services (v0.295 => v0.302)
```

### Detailed test instructions:
1. Checkout this PR, remove the vendors folder and run `composer install` 
2. Run the unit tests locally to confirm they all pass without errors or warnings
3. Test the plugin and the Connection Test page and confirm we can send requests without any fatals or errors (need to connect all accounts)
4. Send both regular requests to Merchant Center and Ads as well as proxied requests in the Connection Test page.
5. In the Settings page disconnect any previously connected Ads Account
6. Onboard the same Ads account again
7. Confirm that all the steps complete without issues
8. Check the option `gla_ads_conversion_action` in the `wp_options DB table, and make sure it contains something like:
```
a:5:{
    s:2:"id";i:987654321;
    s:4:"name";s:46:"[a12b] Google Listings and Ads purchase action";
    s:6:"status";s:7:"ENABLED";
    s:13:"conversion_id";s:12:"AW-12345678";
    s:16:"conversion_label";s:20:"abc_DEF";
}
```
9. View the list of campaigns on the Dashboard page including some report data to confirm that there are no errors when using the update library

### Additional details:

A follow up PR to update the WCS to use API V13 will be created soon.

### Changelog entry
* Update - Google Ads library to API V13. (package v19.1.0)
* Update - Google API Client package to v2.15.
* Update - Google API Client Services package to v0.302.

### CODE REVIEW

**Comment by mikkamp** [comment]
Just wanted to comment on the changelog entry since it's a little confusing:

> * Update - Google Content library to API 2.15.

The API version is staying 2.1 it's just the composer package updating from v2.13.2 to v2.15.0

**Comment by mikkamp** [comment]
Just wanted to leave a note that this PR also resolves: https://github.com/woocommerce/google-listings-and-ads/security/dependabot/66

**Review by mikkamp — APPROVED** [review]
Thanks for the updates, I can confirm that the requests to the API continue functioning as intended with API v13. I also checked the build process, and the final zip file has not increased drastically.

As recommended I'd just suggest to clear up the changelog entry so it's not confusing. Also if I search for v12 there are still a few references to the v12 docs in comments, like:  * https://developers.google.com/google-ads/api/fields/v12/asset_group_asset

It's not a big deal, but we might as well keep them pointing to the latest versions.

In regards to the failing codecov checks a discussion was started [here](p1685527472270039/1685526428.955549-slack-C01E9LB4X61). We are going to look into changing that so they can be ignored here.

**Comment by ianlin** [comment]
> The API version is staying 2.1 it's just the composer package updating from v2.13.2 to v2.15.0

Thanks for the reminder. Updated the changelog and the PR title.

**Comment by ianlin** [comment]
> Also if I search for v12 there are still a few references to the v12 docs in comments,

Updated in the commit 699c72c, thanks for the checking this.

> In regards to the failing codecov checks a discussion was started [here](https://github.com/woocommerce/google-listings-and-ads/pull/p1685527472270039/1685526428.955549-slack-C01E9LB4X61). We are going to look into changing that so they can be ignored here.

Thanks for clarifying, just updated the slack link for above p1685527472270039/1685526428.955549-slack-C01E9LB4X61.

**Pull request merged**
