### PR TITLE
Update the start/end date in the timePeriod message of coupon following google.protobuf.Timestamp

### PR DESCRIPTION
**Pull request by songchen2022**
### Changes proposed in this Pull Request:

Update the start/end date in the TimePeriod message following google.protobuf.Timestamp.
The reason why we update is to keep update with latest content API version and deprecate field that previously used in unstable version.
API will still be backward compatible so there is no worries for merchants who has installed the old version.

### Screenshots:

Screen Shot 2022-02-23 at 9 11 03 AM

Screen Shot 2022-02-23 at 9 43 37 AM

### Detailed test instructions:
1. Go to the coupons Page
2. Select one coupon to edit
3. Fill the coupon expiry date in the coupon data form
4.  Edit the publish time in the publish form in the left top corner, and then click update button
5.  Go back to coupons page and verified the expiry date of the selected coupon is same as what we set

### Changelog entry:

Update the start/end date in  the timePeriod of coupon following google.protobuf.Timestam

### CODE REVIEW

**Comment by findingsimple** [comment]
Hi @songchen2022 

> Screenshots:

Those screenshots are password protected. It's best to just embed them directly in GitHub. It's as simple as dragging and dropping into the editor.

Other
* Could you please add some test instructions so the team has a rough indication of the best way to check it
* Could you please add a changelog entry (we have a pull request template that has the format it in)
* To get a review, please request a review from woocommerce/woogle or woocommerce/ventures

**Review by JPry — COMMENTED** [review]
Code-wise this looks good, but I'd like to be able to test, as [mentioned by Jason](https://github.com/woocommerce/google-listings-and-ads/pull/1260#issuecomment-1048260778).

**Comment by songchen2022** [comment]
> Hi @songchen2022
> 
> > Screenshots:
> 
> Those screenshots are password protected. It's best to just embed them directly in GitHub. It's as simple as dragging and dropping into the editor.
> 
> Other
> 
> * Could you please add some test instructions so the team has a rough indication of the best way to check it
> * Could you please add a changelog entry (we have a pull request template that has the format it in)
> * To get a review, please request a review from woocommerce/woogle or woocommerce/ventures

Thanks so much for your suggestions! Added screenshots, test instructions and changelog entry in the description.

**Comment by songchen2022** [comment]
> Code-wise this looks good, but I'd like to be able to test, as [mentioned by Jason](https://github.com/woocommerce/google-listings-and-ads/pull/1260#issuecomment-1048260778).


Thanks so much for reviewing! Updated the test instructions in the description.

**Comment by songchen2022** [comment]
All the comments have been resolved. Could you please help to review it again? Thanks!

**Comment by JPry** [comment]
I started looking at this again today, and will finish up my testing tomorrow.

**Comment by songchen2022** [comment]
Sounds good. Thanks for taking time to review this.

**Comment by findingsimple** [comment]
@JPry just incase you forgot to hit publish on review

**Review by JPry — APPROVED** [review]
I tested this and confirmed that coupons were uploaded successfully to the merchant center. Good to go!

**Comment by findingsimple** [comment]
I'll go ahead and merge

**Comment by songchen2022** [comment]
> 

Thanks so much for taking care of this!

**Pull request merged**
