### PR TITLE
Display help cursor for `AppTooltip`

### PR DESCRIPTION
**Pull request by ecgan**
### Changes proposed in this Pull Request:

This PR makes `AppTooltip` component display a help cursor when the mouse cursor hovers over the tooltip target.

Credit goes to @puntope for this suggestion in our internal slack thread: p1638280460156000/1638273132.144000-slack-CK365S85V.

`AppTooltip` is used in a few places. See the screenshots below.

### Screenshots:

📹 Demo video showing the interaction in Google Merchant Center section in Setup MC Step 1:

https://user-images.githubusercontent.com/417342/144395033-12ecdc88-2697-41e9-9e40-ba2da220d154.mp4

Dashboard page - Disabled toggle in Free Listings:

image

Product Feed - Edit button:

image

Reports - Products - Info icon. Note that this does not show the help cursor but will show pointer cursor instead because the tabs are anchor `<a>`:

image

### Detailed test instructions:

Visit the above pages, hover your mouse cursor over the tooltip target, and your mouse cursor should change to the help cursor (except the ones in report page). Tooltip should appear as per existing behavior.

### Changelog entry

> Tweak - Display help cursor for tooltip.

### CODE REVIEW

**Comment by ianlin** [comment]
I tried to test it locally but I can't see the Info icon on the Reports page:

Screenshot 2021-12-03 at 11 18 56

Other than that all the question marks are displayed correctly 👍 Will keep checking the code and finish the review.

**Comment by ianlin** [comment]
Replied to myself above: I need to click `Products` in the `Reports` page in order to see the Info icon. 😅

**Review by ianlin — APPROVED** [review]
👍 Tested locally and I can see the question marks and the Info icon.

❔ One of the GH actions checks failed, same happened in other PRs #1134 #1135. 🤔

**Comment by ecgan** [comment]
> ❔ One of the GH actions checks failed, same happened in other PRs #1134 #1135. 🤔

Wondering if it may be due to the use of Node.js 16. 🤔 But then it doesn't affect checks other than bundle size.

image

**Comment by ecgan** [comment]
In the failed bundle size check, I see this line: https://github.com/woocommerce/google-listings-and-ads/runs/4393225657?check_suite_focus=true#step:4:309

> Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/runner/.npm/_cacache/tmp/git-clone5w9XCh/node_modules/@babel/helper-compilation-targets/package.json

I did some google and found some info, looks like we may need to fix it in a separate PR: 

- https://github.com/babel/babel/issues/11216
- [Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /app/node_modules/@babel/helper-compilation-targets/package.json](https://stackoverflow.com/q/62246824/379641)
- [Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in@babel/helper-compilation-targets/package.json](https://stackoverflow.com/q/62081761/379641)

Also, `package-lock.json` was heavily changed in PR #1110 and it was just merged into `develop` branch 14 hours ago, the error might be related to it. 🤔

**Comment by puntope** [comment]
I guess bundle size is already fixed here.

https://github.com/woocommerce/google-listings-and-ads/pull/1133

**Comment by ecgan** [comment]
> I guess bundle size is already fixed here.

Ahh yes, I just happen to see that and was about to comment the same. 😄

**Pull request merged**
