### PR TITLE
Streamline campaign setup: Update budget recommendation text

### LINKED ISSUE #2600: Review budget recommendation text
Following the removal of the Ads Audience section in #2501, the budget recommendation text has become unclear, as users can no longer select or view the countries targeted for their ads.

image

## Acceptance Criteria

- [ ] The text should be updated to "Google will optimize your ads to maximize performance. Tip: Most merchants who sell products on similar countries set a daily budget of $X"

## Implementation Brief
* Update `BudgetRecommendation` to set the recommended budget text as per the AC.

## Test Coverage
* Tests should be updated if necessary.

### PR DESCRIPTION
**Pull request by kt-12**
### Changes proposed in this Pull Request:

Closes #2600 .

Text updated to reflect the change. Check screenshot.

### Screenshots:

**Multiple Counties selected**
Screenshot 2024-09-30 at 10 42 21

**Single country selected**
Screenshot 2024-09-30 at 10 42 13

### Detailed test instructions:

1. On "Create your paid campaign" page select single country
2. Check if the text change is reflected.
3. Now select an additional country and see if the text is same as shown in the screenshot above. 

### Changelog entry

>

### CODE REVIEW

**Review by asvinb — APPROVED** [review]

**Comment by asvinb** [comment]
LGTM @kt-12

**Comment by ankitguptaindia** [comment]
Changes Look good and working as expected.  ✅ 

https://github.com/user-attachments/assets/acfcb78e-7ba7-43c5-97b0-a1f39e74dd69

**Review by ankitguptaindia — APPROVED** [review]

**Review by eason9487 — COMMENTED** [review]
Hi @kt-12, the change looks good.

Could you make this PR not include file changes that don't belong to it?

**Comment by kt-12** [comment]
@eason9487  I am unsure how those commits ended up here. This was not the case till after 10upCR. I have removed those commits. It's good for WooCr review now.

**Review by eason9487 — APPROVED** [review]
LGTM

**Pull request merged**
