### PR TITLE
Feature Gtag Events

### LINKED ISSUE #1404: Add Woocommerce gTag remarketing and conversion signals
## User story
We want to add gTag info in home/product/cart/purchase/add_to_cart page to support remarketing for retail and enhanced ecommerce conversion tracking .

Existing gTag implementation injected GTag script generally in all pages, and implemented barely conversion signals for purchase. Because of missing signals of product visits, add_to_cart events and cart visits, Google’s prediction system won’t be able to rank the merchant sites/their offers as high quality sources. 

Therefore, we would like to identify the data source of required parameters within the WooCommerce system, and work on injecting those signals appropriately on product/cart/purchase pages to help increase ecommerce conversion tracking. 

### Is your feature request related to a problem? 

Existing gTag implementation injected GTag script generally in all pages, and implemented barely conversion signals for purchase. Because of missing signals of product visits, add_to_cart events and cart visits, Google’s prediction system won’t be able to rank the merchant sites/their offers as high quality sources. 

### Describe the solution you'd like 

- Config the account and fire the page_view event on every page. 
- Fire the tag, passing ecomm_pagetype='product' and products information in product page
- Fire the tag passing ecomm_pagetype='cart' and the information of products after the user click the add to cart button
- Fire the tag passing ecomm_pagetype='cart' and the information of products of cart in cart page
- Pass ecomm_pagetype='purchase' and additional conversion information in order confirmation page

### Describe alternatives you've considered 

N/A

## Technical

Screen Shot 2022-04-05 at 10 39 59 AM
Screen Shot 2022-04-05 at 10 40 25 AM
Screen Shot 2022-04-05 at 10 40 47 AM
Screen Shot 2022-04-05 at 10 41 10 AM
Screen Shot 2022-04-05 at 10 41 42 AM

## Figma link

TBC

## Acceptance criteria

TBC

## Unknowns

TBC 

## Out of bounds/rabbit holes

TBC

## Event tracking

TBC

### PR DESCRIPTION
**Pull request by mikkamp**
### Changes proposed in this Pull Request:

PR to keep track of all the PR's related to the Gtag events:
- #1329 
- #1488 
- #1533 
- #1550 
- #1554

Closes #1404

### Detailed test instructions:
See smoke testing steps in [wiki](https://github.com/woocommerce/google-listings-and-ads/wiki/Smoke-tests#gtag-events-covered-by-e2e-tests-but-can-be-tested-manually)

### Changelog entry
* Add - Gtag event tracking.

### CODE REVIEW

**Comment by mikkamp** [comment]
@songchen2022 This is the combined feature branch which contains all the Gtag event tracking code (including automated testing). Would you be able to test the events based on the wiki instructions and confirm that they satisfy all the requirements in #1404
Let me know if there is still anything missing.

**Comment by songchen2022** [comment]
@mikkamp  Thanks for your help. Could I know which wiki instructions you mentioned?

**Comment by songchen2022** [comment]
> 

Hi @mikkamp, thanks so much for helping to work on it. I tested the events based on the wiki instructions and confirm that they satisfy all the requirements of sending signals gtag from Woocommerce websites. We don't test the receiving signals now. 

After internal discussion, we're good to merge this. Please let me know is there anything I could do. Thanks！

**Comment by findingsimple** [comment]
Thanks @songchen2022 - Is there any documentation that should be updated to go with these changes before we release?

**Comment by findingsimple** [comment]
Please hold off merging until we hear back about documentation and some internal discussion around consent.

**Comment by songchen2022** [comment]
@jconroy @mikkamp  Sorry for the late reply. I tested the feature following the wiki doc. Please refer to this [doc](https://docs.google.com/document/d/1aqrXZtMdoZ2Z-QdF0yHIHDMkeLwhHaDX8oaPcceh8f4/edit?resourcekey=0-aWk2FQTuMwrE-k3VOM9ibg#heading=h.336brqdjc029) and welcome any comments and suggestions.

**Pull request merged**
