### PR TITLE
Free Listings + Paid Ads: UI updates for get started page and onboarding flow

### LINKED ISSUE #1143: "Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>." in Tip in Setup MC
### Describe the bug:

If we open browser dev tools and visit the Setup MC page, we would see the following error message in the console: `"Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>."`

image

This is because we are using the `@wordpress/components`' Tip component (https://github.com/WordPress/gutenberg/blob/9faa63ec01c7db4e4d57823af2db5c54bb6d6660/packages/components/src/tip/index.js), which generates the `<p>` tag. [Inside our usage of `<Tip>`](https://github.com/woocommerce/google-listings-and-ads/blob/9e7066e78ceac80971f228000e8a187c3add2b0d/js/src/setup-mc/setup-stepper/setup-accounts/google-mc-account/index.js#L21-L39), we also have an `<AppTooltip>` which generates `<div>` tag.

IMO, the Tip component should generate `<div>` tag instead, which would be more lenient and be able to accommodate any child content.

Note that the actual work should be done in the https://github.com/WordPress/gutenberg repo, not this plugin repo.

### Expected behavior:

The Tip component should not genarate the `<p>` tag. Instead, it should generate a wrapper `<div>` tag.

### Actual behavior:

The Tip component generates a `<p>` tag and wraps the contents that we passed in containing `<div>` tag, causing the warning to show up in the browser console.

### Steps to reproduce:

1. Open browser dev tools. 
2. Visit Setup MC Step 1.
3. The warning should appear in the browser console.

### PR DESCRIPTION
**Pull request by eason9487**
### Changes proposed in this Pull Request:

This PR implements parts of **📌 Update other UI changes** in #1610.

- Adjust layouts for `StepContentHeader` component.
- Adjust layouts and copywriting for the get started page.
- Adjust layouts and copywriting for onboarding steps of accounts setup, product listings configuration, and store requirements confirmation.
- Change the logos for account cards of Google Merchant Center and Ads.

Closes #1143

- The use of `Tip` component is removed from the accounts setup step.

### Detailed test instructions:

💡 This PR only doesn't contain logic changes.

Compare the get started page and the onboarding flow with Figma doc fqR0EHi63lWahRcVTKCcba-fi-4%3A36753 (the i3 FL+Ads Post UXR group) to see if the copywriting is the same, and whether the visual is similar.

### Changelog entry

> Update - Layouts and copywriting of the Get Started page and the onboarding flow.
> Update - Logos of Google Merchant Center and Google Ads.
> Fix - A validateDOMNesting warning in the accounts setup step of the onboarding flow.

### CODE REVIEW

**Comment by puntope** [comment]
❓ 

In Get Started page - In Customer quotes section l I see

"21,000+ WooCommerce store owners like you already list products on Google for free"

However in Figma design it's

"21,000+ WooCommerce store owners like you already list products with Google"

We should remove "for free"

**Comment by puntope** [comment]
❓  

In regards COntent Header stepper. `js/src/components/stepper/step-content-header/index.js` 

I see in figma it shows the step number as well. 

Screenshot 2022-08-12 at 15 24 06

**Comment by puntope** [comment]
❓ In Connect step.

I see "Required to sync products and list on Google Shopping"

But in Figma is "Required to sync products and list on Google"

**Comment by puntope** [comment]
❓ 

In shipping rates description on Step 2

It says "Your shipping rates will be shown to potential customers on Google."

In figma it says

"Your estimated shipping rates and times will be shown to potential customers on Google. "

Screenshot 2022-08-12 at 15 37 55

**Comment by puntope** [comment]
❓ The pre-launch checklist in the step 3 is different visually and in content.

**Comment by eason9487** [comment]
@puntope, thanks for reviewing and catching these missed copywriting changes! 🙏 

https://github.com/woocommerce/google-listings-and-ads/pull/1618#issuecomment-1213082190, https://github.com/woocommerce/google-listings-and-ads/pull/1618#issuecomment-1213115101, https://github.com/woocommerce/google-listings-and-ads/pull/1618#issuecomment-1213120606 these three were updated in https://github.com/woocommerce/google-listings-and-ads/pull/1618/commits/25a7d8ae714ed7e0495a77c0507eeb113ff4c167.

> In regards COntent Header stepper. `js/src/components/stepper/step-content-header/index.js`
> I see in figma it shows the step number as well.
> Screenshot 2022-08-12 at 15 24 06

The step number captions were decided to be removed in #923, but some Figma files are not updated yet.

> ❓ The pre-launch checklist in the step 3 is different visually and in content.

The pre-launch checklist will be changed by the Policy Compliance Checks project (#1612).

**Review by puntope — APPROVED** [review]
✅  LGTM

Thanks for the changes. This is ready to go

**Pull request merged**
