### PR TITLE
Remove free shipping options from MC settings

### PR DESCRIPTION
**Pull request by nima-karimi**
### Changes proposed in this Pull Request:

This PR removes the `offers_free_shipping` and `free_shipping_threshold` options from Merchant Center settings. These options are now managed in the shipping settings for each country separately, and they do not need to be set globally anymore.

Related to #1171.

### Changelog entry

>

### CODE REVIEW

**Comment by puntope** [comment]
The code looks good. But I was unable to test it. Not sure about the procedure for testing this.

I was looking at #1171 and I tried to follow the testing instructions there... but I was unable to perform the API calls as expected. 

For example: 

POST `wp-json/wc/gla/mc/shipping/rates` with the body as indicated in the testing procedure but I got this response:

```
{
    "code": "rest_missing_callback_param",
    "message": "Missing parameter(s): country, method, rate",
    "data": {
        "status": 400,
        "params": [
            "country",
            "method",
            "rate"
        ]
    }
}
```

**Comment by nima-karimi** [comment]
I don't think any testing is necessary for this PR as it's only removing references to variables previously removed by another PR. Sorry, I probably should've mentioned this in the PR description.

**Comment by puntope** [comment]
> I don't think any testing is necessary for this PR as it's only removing references to variables previously removed by another PR. Sorry, I probably should've mentioned this in the PR description.

I understand that there are just line removals but sometimes that could create issues or errors in a part of code that referenced those variables. That's why I asked about a happy path or procedure to check that everything is still smooth.

**Comment by nima-karimi** [comment]
Well, I think you can confirm that providing the two mentioned options to the `POST mc/settings` API will actually not save them.

**Review by puntope — APPROVED** [review]
✅ LGTM 

- I was able to set up the GLA Account 

❓ Not related to this issue probably but yes to the parent issue

In the GLA Account setup, I saw this in the logs. Maybe worth it to take a look

Screenshot 2022-01-26 at 17 46 13

**Comment by nima-karimi** [comment]
Thanks for the review @puntope 🙏 

> In the GLA Account setup, I saw this in the logs. Maybe worth it to take a look

Yes, this is likely due to changes in the APIs. Since the base branch introduced some major changes to the rates APIs. @ecgan is currently modifying the UI to work with those changes.

**Pull request merged**
