### PR TITLE
Add `eslint-plugin-import` to help catch JS import errors

### PR DESCRIPTION
**Pull request by ecgan**
### Changes proposed in this Pull Request:

This PR serves as a workaround to address my comment in https://github.com/woocommerce/google-listings-and-ads/pull/899#issuecomment-885033942. It adds [`eslint-plugin-import`](https://www.npmjs.com/package/eslint-plugin-import) and uses the recommended config to help us catch import errors in JavaScript side. 

Note that the file `.eslintrc` has also been renamed to `.eslintrc.js`. This is consistent with Gutenberg and WC Admin.

The approach used in this PR is also used in WC Admin, where they have manual install `eslint-plugin-import` package. We are using `plugin:import/recommended` config, whereas they are using manual individual rules configuration. See links below:

https://github.com/woocommerce/woocommerce-admin/blob/0f6eafcfa3dfbc4c7807210ef1056440d896654d/package.json#L213

https://github.com/woocommerce/woocommerce-admin/blob/0f6eafcfa3dfbc4c7807210ef1056440d896654d/.eslintrc.js

### Screenshots:

Before this PR, if you import something that doesn't exist, there is no error and warning, and might lead to runtime error in production:

image

With this PR, there will be eslint error:

image

### Detailed test instructions:

1. Checkout this PR. 
2. Open a JS file and import something that does not exist, e.g. `import { Button } from '@wordpress/element';`
3. There should be an ESLint error on the wrong import.

### Changelog entry

> Fix: add eslint-plugin-import to help catch JavaScript import errors.

### CODE REVIEW

**Comment by tomalec** [comment]
WDYT of proposing an upstream change to WC Admin, to use this setup as well? I think it would be nice to **eventually** have your linter configured as close as possible & convenient :)

**Comment by tomalec** [comment]
> Note that the file `.eslintrc` has also been renamed to `.eslintrc.js`. This is consistent with Gutenberg and WC Admin.

Are there any benefits for having it as `.js`, other than consistency with Gutenberg and WC Admin?

Personally, I find the CJS `module.exports` syntax an eye-sore of prehistoric legacy, that ties us back to the pre-ESM, hard to debug, bundler-heavy world ;). I think we should use the fact, we have a smaller scope, and are more agile to modernize the stack, and erode the code towards the latest syntax. 
Also, as long as we do not need any dynamic or imperative parts, I like the simplicity of declarative JSON, which shouts: "Hey, I'm boring and static!"

**Comment by ecgan** [comment]
> Are there any benefits for having it as `.js`, other than consistency with Gutenberg and WC Admin?

> I like the simplicity of declarative JSON

There are actually two points in the renaming. 

Point 1 is about the file extension. Previously, the file name is `.eslintrc`. Without a proper file extension like `.js` or `.json`, some tools like prettier do not work nicely and automatically.

Point 2 is about the file content / structure, whether we want to use `.js` with `module.exports`, or `.json`. 

One thing I would like to point out is that with `.js`, we can put inline comments in it easily (e.g. to explain why certain configurations are set that way); whereas with `.json`, comments are not allowed, strictly speaking (there are ways to make it work though, but they are not standard and they require effort).

So with this perspective, I'm leaning slightly towards `.js`, even though I am fine with `.json` really.

**Comment by ecgan** [comment]
> WDYT of proposing an upstream change to WC Admin, to use this setup as well? I think it would be nice to **eventually** have your linter configured as close as possible & convenient :)

Yup, and that's what I have been looking at and working on too (I mentioned this in my daily update in our team Slack channel), but apparently it's more complicated than I thought, and I think it would require some discussions within the WC Admin repo to figure things out, and it would take some time to get it published in npm. That's why in the PR description I mentioned "this PR serves as a workaround".

When the changes is done in WC Admin and published in npm, we can then remove this workaround. 🙂

**Comment by ecgan** [comment]
Created related issue https://github.com/woocommerce/woocommerce-admin/issues/7415 and PR https://github.com/woocommerce/woocommerce-admin/pull/7416 for `@woocommerce/eslint-plugin`.

**Comment by tomalec** [comment]
> Point 1 is about the file extension. Previously, the file name is `.eslintrc`. Without a proper file extension like `.js` or `.json`, some tools like prettier do not work nicely and automatically.

Yup, I totally agree, whichever way we go, adding an extension is nice.

> Point 2 is about the file content / structure, whether we want to use `.js` with `module.exports`, or `.json`.
>
> One thing I would like to point out is that with `.js`, we can put inline comments in it easily 

Ok, I totally buy that :) Migrating CJS to ESM eventually for that file should be straight forward.

**Review by tomalec — APPROVED** [review]
Tested locally, reviewed the code LGTM.

**Pull request merged**
