### PR TITLE
Replace `@wordpress/dependency-extraction-webpack-plugin` with `@woocommerce/dependency-extraction-webpack-plugin`

### LINKED ISSUE #916: Consider switching to **`@woocommerce/`**`dependency-extraction-webpack-plugin`
Currently we use `@wordpress/dependency-extraction-webpack-plugin` in quite outdated version, to [wrangle](https://github.com/woocommerce/google-listings-and-ads/blob/trunk/webpack.config.js#L19-L20) WooCommerce components.

So far there is no problem directly connected to it. But I recall struggling with some `/components` dependencies in the past (like https://github.com/woocommerce/google-listings-and-ads/pull/234).

After reading a comment https://github.com/saucal/pinterest-for-woocommerce/pull/105/files#r678799560 I think it may be worth changing it here, to save us some problems in the future, plus maybe workaround WP package update related problems https://github.com/woocommerce/google-listings-and-ads/pull/821

### PR DESCRIPTION
**Pull request by tomalec**
### Changes proposed in this Pull Request:

Replace Dependency Extraction Webpack Plugin from [`@wordpress/dependency-extraction-webpack-plugin`](https://www.npmjs.com/package/@wordpress/dependency-extraction-webpack-plugin) to [`@woocommerce/dependency-extraction-webpack-plugin`](https://www.npmjs.com/package/@woocommerce/dependency-extraction-webpack-plugin).

Simplify webpack config a bit.
Reduce the bundle size - index.js weighs 48,5% less

Fixes https://github.com/woocommerce/google-listings-and-ads/issues/916

### Screenshots:

image

### Detailed test instructions:

1. checkout this branch
2. `npm install && npm run build`
3. `npm run test-unit && npm run test:e2e`
4. Smoke test the plugin to check that WP and WC components are rendered correctly :confused: 

### Changelog entry

> Fix - Stop bundling Woo components. Replace `@wordpress/dependency-extraction-webpack-plugin` with `@woocommerce/dependency-extraction-webpack-plugin`.

### CODE REVIEW

**Review by ecgan — APPROVED** [review]
Tested as per test instructions, LGTM 👍

**Review by eason9487 — COMMENTED** [review]
❓ 
By this change, the runtime `@woocommerce/tracks` would be `wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/tracks/index.js`, or `wp-content/plugins/woocommerce-admin/dist/tracks/index.min.js` if the site installed the *WooCommerce Admin* plugin. If event tracking in the WC Settings is enabled during development and the runtime one is not a development build, then the tracking events in developing/debugging/programming will actually be sent to the production endpoint of event tracing. Not sure would it be a concern if we might send non-production tracking events accidentally.

Ref: https://github.com/woocommerce/woocommerce-admin/blob/v2.1.5/packages/tracks/src/index.js#L31

---

❓ 
Although this can reduce the bundle size a lot, we would face with all these deps, `@woocommerce/currency`, `@woocommerce/data`, `@woocommerce/date`, `@woocommerce/number`, and `@woocommerce/tracks`, at runtime are using the versions which are determined by the installed version of *WooCommerce* or *WooCommerce Admin*. And in addition, the versions become a range from fixed, and they would also be dynamic versions ranges over time.

From the experience of using extracted `@woocommerce/components`, this would also make it take more time to investigate users' runtime versions when they report errors to HE and us. The dependency versions for unit testing are still the fixed versions specified in package.json, which, in addition to being inconsistent with the development version, may also make our testing unreliable because I guess we couldn't test a range of dependencies' versions in the unit test.

I took much time to check if there are any breaking changes by looking into their versions within the *Woocommerce Admin* version from 2.1.5 to 2.5.1. And it seems ok that the breaking changes noted on CHANGELOG or README would not affect our usage, some of their ranges have across primary version numbers though. While the bundle size can be reduced by almost 50%, if the trade-off is that the complexity of development, testing, and debugging would become higher, and I don't think it's worth the adjustment.

**Comment by tomalec** [comment]
Thanks for catching that @eason9487!
>  If event tracking in the WC Settings is enabled during development and the runtime one is not a development build, then the tracking events in developing/debugging/programming will actually be sent to the production endpoint of event tracing. Not sure would it be a concern if we might send non-production tracking events accidentally.

One thing is catching development events, which probably has some chance to be acceptable. But I guess gating events from automated e2e tests would be too much.

:construction:  So it looks like a showstopper to me. But maybe we can enable dev mode of those packages otherwise...

**Comment by tomalec** [comment]
> Although this can reduce the bundle size a lot, we would face with all these deps, …

I agree that struggling with unpredictable and hard to match version-ranges of those packages will be a hassle.

I only wonder who should pay the price of instability of components and version integrations between our plugins: 
- us - developers, or
- merchants

We already face that struggle with `wordpress/components` don't we?
So currently we rely on the stability of `WP/components`, but play safe and bundle `Woo/components`. I wonder if that's a conscious inconsistency.

> While the bundle size can be reduced by almost 50%, if the trade-off is that the complexity of development, testing, and debugging would become higher, and I don't think it's worth the adjustment.

The size is one metric, the other is time/resources spend on scripting:

Screenshot from 2021-08-25 17-20-18
Screenshot from 2021-08-25 17-20-24

**Comment by tomalec** [comment]
In the Pinterest for WC PR (105-gh-woocommerce/pinterest-for-woocommerce #discussion_r67879956) @samueljseay suggested that:
> […] you should be safe not to bundle WordPress or WooCommerce packages in the webpack config

I'm not sure what's policy we should take here:
- Bundle everything bloating the user, but serving better assured quality,
- Unbundle, and somehow unit- & e2e-test with variety of versions

**Comment by haszari** [comment]
> If event tracking in the WC Settings is enabled during development and the runtime one is not a development build, then the tracking events in developing/debugging/programming will actually be sent to the production endpoint of event tracing. Not sure would it be a concern if we might send non-production tracking events accidentally.

(Side note) FYI – the event tracking system is robust to developer/testing events. You shouldn't need to worry about preventing events from non-production sites. There are a few ways of detecting test sites implemented in the ingest engine, and in general the system is tolerant to noise because of scale.

**Comment by tomalec** [comment]
To gather more voices and ideas, I created a post on our internal blog (pb0Spc-1LK-p2)

**Comment by tomalec** [comment]
Closed in favor of https://github.com/woocommerce/google-listings-and-ads/pull/1526 which only replaces the package used, leaving the bundle intact.

To continue the work regarding bundled packages I created https://github.com/woocommerce/google-listings-and-ads/issues/1527

**Pull request closed without merging**
