### PR TITLE
Feature - Policy Compliance Checks

### PR DESCRIPTION
**Pull request by mikkamp**
Changes for the Policy Compliance Checks:

- #1532 
- #1563 
- #1611 
- #1612 
- #1622

### CODE REVIEW

**Comment by mikkamp** [comment]
@songchen2022 I've created this draft PR containing all the PR's for the Policy Compliance Checks. Would you be able to clarify if this covers all the desired functionality. As well as specify any manual tests which are needed to confirm it's functioning as it should.

Once that's completed we can work on getting this ready to be included in a release.

**Comment by songchen2022** [comment]
@mikkamp Thanks so much for creating this PR. I think the PR covers all the desired functionality. I will share the doc about the desired functionality soon.

**Comment by songchen2022** [comment]
https://docs.google.com/document/d/1V2gtwai-mPQsoO22_C1uoMsIo5JOwfKE4Dqo9go9UoY/edit?resourcekey=0-5pAYz06ALHMDvDcGS6bf_g
@mikkamp  I created a doc about general manual tests what we could confirm. Please let me know if anything I missed. Thanks!

**Comment by eason9487** [comment]
Did a few rounds of overall testing and it worked well.

- Most of the titles, contents and links of check items are the same as those on Figma.
   - Found three typos and opened PR #1708 for it.
- The wording logic of the first person and second person is shown as expected.
- The pre-selecting processing is successfully performed.
- All interactions like clicking confirm buttons and checkboxes work correctly.
- Onboarding flow can be completed.
- Found four unused JS hooks and opened PR #1707 to remove them.

**Comment by songchen2022** [comment]
Thanks so much for the testing and fixing! Let me know if anything I could do and anything from our side.

**Pull request merged**
