### PR TITLE
Run PHPCS checks for unit tests

### LINKED ISSUE #1623: Run PHPCS for unit test code
## User story

Currently the PHPCS rules are ignored for all the code in the unit tests folder. However it can be useful to keep code standards for the unit tests as well, especially the rules for spacing and code formatting which make it easier to read the code.

The suggestion is to create a second PHPCS configuration file which will be used for checking the code in the unit tests folder. Rules for doc blocks can be turned off as well as any other rules which don't apply directly to unit tests.

### Tasks to complete

- [x] Create a second PHPCS configuration file for unit tests.
- [x] Ensure IDE's will be able to automatically pick up the configuration files.
- [x] Add a second PHPCS check in the GitHub actions which uses the configuration file for unit tests.
- [x] Make sure the tests folder is not excluded from detecting any PHP changes in GitHub actions.
- [x] Fix the current unit tests to pass PHPCS rules.

### PR DESCRIPTION
**Pull request by mikkamp**
### Changes proposed in this Pull Request:

This PR adds automated PHPCS checks for unit tests, to ensure we stick with consistent code. Since writing doc blocks isn't useful for unit tests, this PR adds a second configuration file with custom rules for the unit tests.

Closes #1623 

### Detailed test instructions:
1. Check the tests at [this point](https://github.com/woocommerce/google-listings-and-ads/runs/7770089587).
2. Confirm that the step "Run PHPCS on all tests" was run and failed.
3. Check the tests at the end of the PR and confirm they all passed.
4. Run `npm run lint:php-tests` locally and confirm it passes.
5. Run the unit tests `vendor/bin/phpunit` locally and confirm they pass.

### Changelog entry
* Dev - Run PHPCS checks for unit tests.

### CODE REVIEW

**Review by puntope — APPROVED** [review]
✅  LGTM

- Tested locally 
- Checked the rules
- Checked creating an "issue" with an excluded rule and tested it doesn't generate any errror
- Checked creating an issue ad it generated an error.

**Comment by puntope** [comment]
❓  I'm wondering if we should add also something for apply PHPCBF to Test files.

**Comment by mikkamp** [comment]
> I'm wondering if we should add also something for apply PHPCBF to Test files.

Would you be able to clarify what you mean? Do you mean adding a script in `package.json` for automatically fixing the errors?
It can be run easily with `cd tests` and then run `../vendor/bin/phpcbf`, it will pick up the local configuration file for tests.

I think most people have it setup in their IDE to run phpcs automatically which will also pick up the tests configuration file and highlight the errors within the IDE, so I personally fix as I write the code and don't run `phpcbf`.

image

**Comment by puntope** [comment]
> Would you be able to clarify what you mean? Do you mean adding a script in `package.json` for automatically fixing the errors? It can be run easily with `cd tests` and then run `../vendor/bin/phpcbf`, it will pick up the local configuration file for tests.

Sometimes when running the PHPCS in console it says "21 of this errors can be fixed by PHPCBF" so wonder if it could be a nice to have to have that custom script specific for unit tests rules. (So not the global one in `../vendor/bin/phpcbf`) 

PS. This is not a blocker so the PR can be merged 👌

**Comment by mikkamp** [comment]
Thanks for the clarification. I guess we can discuss it a bit more and enable it in a follow PR if needed. My opinion differs though, I prefer not to have phpcbf run automatically. Mainly because it doesn't encourage improving your writing style, as it will get auto fixed anyway.

**Comment by puntope** [comment]
>  I prefer not to have phpcbf run automatically. Mainly because it doesn't encourage improving your writing style, as it will get auto fixed anyway.

Not sure what do you mean with automatically. My suggestion is basiaclly to have a `npm run lint:php-cbf`

As far as I undertand it will use the rules of Testing PHPCS  for the test files and the global PHPCS for the rest of the code automatically.

**Comment by mikkamp** [comment]
> My suggestion is basically to have a `npm run lint:php-cbf`

Added in https://github.com/woocommerce/google-listings-and-ads/pull/1624/commits/963f01dab462e7baed29fb7aed23753389fdd865

**Pull request merged**
