### PR TITLE
Sync products for all target countries

### PR DESCRIPTION
**Pull request by nima-karimi**
### Changes proposed in this Pull Request:

Part of #14.

This PR modifies the ProductSyncer to take into account the target audience countries the user has set when submitting products. This means that each product is now submitted for all of the countries that the user has set as their target audience in the configurations/onboarding step.

Google assigns each product+targetCountry combination a unique ID, meaning that we have a one-to-many relationship between WooCommerce product IDs and Google IDs. The IDs are stored as an array in the `_wc_gla_google_ids` meta.

When a user tries to delete the product from Google MC (i.e. not sync it anymore), we might send several batches of delete requests to Google with all of the Google IDs.

In case of any errors while syncing/deleting a product there are actions that are triggered and schedule a second update/delete job with just the errored products. We only retry the update/delete if the error is of type "Internal Error", which is basically a Google backend error. This error has appeared several times during my testing especially once the number of products that are submitted is large (the batch size is still way less than the recommended size of 1000 so the error seems to be unrelated to the request).

In order to avoid any timeouts, the size of each batch when submitting products is set based on the number of target audience countries set by the user.

### Detailed test instructions:

1. Make sure you have the `gla_mc_setup_completed_at` option set to a timestamp in `wp_options` table. (i.e. your merchant center set up is completed)
1. Go to Marketing > Google and select some target countries or "All Countries" from the "Choose your audience" step
1. ~~Go to the Connection Test page and initiate an async product syncing job.~~ A job called `gla/jobs/refresh_synced_products/create_batch` should be scheduled to resubmit the products to Google MC
1. Wait for the job to complete. There might be several jobs and they may take a while to complete if you have many products/variations and/or many target countries.
1. Check Google Merchant center and under "Feeds" make sure that all target countries have an equal number of submitted products
1. If they don't have an equal number of products per country, it might be due to some syncing errors. If the errors are of type "Internal Error" there is a job implemented that tries to resync those products until they get synced. However, if the error is any other type, the products may not be synced for some countries (e.g. validation errors specific to some countries).

Note that the synchronous mode of syncing might not work properly if your number of products or the number of target countries is large. You may hit a time-out error if you use the synchronous mode.

### To do:

- [x] Make sure the delete job deletes all products from all countries (+ optimize it)
- [x] Refresh the product feed once the target country changes (i.e. remove it from a country if the user deselects it as a target)
- [x] Fix the RefreshProducts job queued multiple times on audience change

### CODE REVIEW

**Review by JPry — CHANGES_REQUESTED** [review]

**Review by JPry — CHANGES_REQUESTED** [review]
Thanks for the updates @nima-karimi. The code changes look OK, but there's an error on the action when I let the job run. Once that is fixed I definitely want to run the process again to double check all is working as expected.

**Review by JPry — CHANGES_REQUESTED** [review]
The only major problem I'm seeing are the additional classes requiring the `ContainerAwareInterface` implementation. I left a note about the ones I found.

**Review by findingsimple — COMMENTED** [review]
Ran through initial another test sync this morning (using https://github.com/woocommerce/google-listings-and-ads/pull/367 as my base) - products and variations all looked to be synced correctly for multiple countries using the Woo test store products.

Didn't see any errors.

---

However, when I tried updating a variable product I got the following with a failed scheduled action

```
[29-Mar-2021 00:35:21 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Automattic\WooCommerce\GoogleListingsAndAds\Product\ProductHelper::get_visibility() must be an instance of WC_Product, int given, called in /Users/jconroy/Repos/google-listings-and-ads/src/Product/BatchProductHelper.php on line 156 and defined in /Users/jconroy/Repos/google-listings-and-ads/src/Product/ProductHelper.php:157
Stack trace:
#0 /Users/jconroy/Repos/google-listings-and-ads/src/Product/BatchProductHelper.php(156): Automattic\WooCommerce\GoogleListingsAndAds\Product\ProductHelper->get_visibility(97)
#1 /Users/jconroy/Repos/google-listings-and-ads/src/Product/ProductSyncer.php(64): Automattic\WooCommerce\GoogleListingsAndAds\Product\BatchProductHelper->validate_and_generate_update_request_entries(Array)
#2 /Users/jconroy/Repos/google-listings-and-ads/src/Jobs/UpdateProducts.php(46): Automattic\WooCommerce\GoogleListingsAndAds\Product\ProductSyncer->update(Array)
#3 /Users/jconroy/Repos/google-listings-and-ads/src/Jobs/AbstractActionSchedulerJob.php(77): Automat in /Users/jconroy/Repos/google-listings-and-ads/src/Product/ProductHelper.php on line 157
```

**Review by JPry — APPROVED** [review]
Code looks good, and I tested and saw my products uploaded to the Merchant Center for multiple countries. 🚀

**Pull request merged**
