### PR TITLE
Remove PMax Migration Banners

### PR DESCRIPTION
**Pull request by jorgemd24**
### Changes proposed in this Pull Request:

PMax Migration banners were still showing even though the migration ended in September last year. 

This PR removes the PMax migration banner and it is aligned with the following PR https://github.com/woocommerce/google-listings-and-ads/pull/1798 that removed the inbox notifications about the migration. 

#### Dashboard
image

#### Reports
image

### Detailed test instructions:

1. Go to the dashboard page, and the banner should not be displayed.
2. Go to the reports page, and the banner should not be displayed.

If you would like to test that banners were showing in develop branch follow these steps:

 1. Remove the following items from the local storage (in case they were dismissed previously): 
-  `localStorage.removeItem('gla-is-before-migration-notice-dismissed')`
-  `localStorage.removeItem('gla-is-after-migration-notice-dismissed')`
- `localStorage.removeItem('gla-is-reports-migration-notice-dismissed')`
2. Go to the dashboard or the reports page and the banner should be displayed. 

### Changelog entry

> Tweak - Remove unnecessary PMax migration banners

### CODE REVIEW

**Comment by puntope** [comment]
👀  Are we using `js/src/utils/getConversionCampaignStatusNotice.js`?  if not we can consider remove it and the attached tests.

**Comment by puntope** [comment]
If we end up deleting `js/src/utils/getConversionCampaignStatusNotice.js` as suggested here https://github.com/woocommerce/google-listings-and-ads/pull/1889#issuecomment-1432792151

Also we might remove `CAMPAIGN_ADS_MIGRATION` constant.

**Review by puntope — COMMENTED** [review]
@jorgemd24 Thanks for working on this.

I don't see anymore the notice. However, there are some residual files and a constant we might consider for deletion. (check comments)

**Comment by jorgemd24** [comment]
Thanks @puntope for catching this.

At this point, all campaigns should be converted so I think it is not necessary to keep the hook.

I removed the hook and the constant.

**Review by puntope — APPROVED** [review]
✅  LGTM 

Good job

**Pull request merged**
