### PR TITLE
Guzzle Conflict with other plugins

### LINKED ISSUE #751: Incompatible with Bookings
### Describe the bug:
As a followup to https://github.com/woocommerce/google-listings-and-ads/pull/750 where we show an admin notice when the Bookings extension is active.

Ideally we should be able to continue functioning without conflicting, if the `guzzlehttp/guzzle` library is only loaded as needed. Our extension needs it only for sending requests to WCS, so we should check if Bookings can only load this library when it's actually sending/retrieving data to/from the Google API.

### Expected behavior:
No fatal error to occur and the two extensions to work in harmony.

### Actual behavior:
We get an incompatibility notice to prevent a fatal error from occurring when both plugins are active. See: https://github.com/woocommerce/woocommerce-bookings/issues/3004

### PR DESCRIPTION
**Pull request by mikkamp**
### Changes proposed in this Pull Request:

This PR ensures that we use a unique namespace for the Guzzle library so we do not conflict with any other plugins that might be using different versions of the same library. Since we not only use the Guzzle library directly, but it's also used by the Google Content API and the Google Ads library, this PR adds some code for replacing namespaces in dependent libraries.

The following points are done in this PR:
- Use a unique namespace for Google\Auth
- Use a unique namespace for GuzzleHttp
- Add dependencies for each of the above two
- Prefix the namesapce for direct usage in the code (ex. `\GuzzleHttp\Psr7\stream_for`)
- When prefixing `namespace` and `use` statements, match the whole word (prevents Google\Auth from matching Google\AuthHandler)
- Removes incompatibility warning for Bookings

Closes #751 

### Detailed test instructions:

1. Checkout PR
2. run `rm -rf vendor && composer install`
3. Use the connection test page to check requests sent directly to WCS
4. Use the connection test page to send proxied requests to the Content API
5. Use the connection test page to send proxied requests to the Ads API library
6. Activate the Bookings plugin and confirm we no longer see an admin warning

Ideally those three types of requests should function without any errors or warnings. However the changes are quite substantial, so ideally we would test any requests that gets sent to an API (through Guzzle).

I've tested with the following list of conflicting plugins, which would previously give an error upon activation:
https://woocommerce.com/products/woocommerce-bookings/
https://wordpress.org/plugins/backwpup/
https://wordpress.org/plugins/simple-sales-tax/
https://wordpress.org/plugins/mailjet-for-wordpress/

### Changelog entry
* Fix - Resolve Guzzle Conflict with other plugins.

### CODE REVIEW

**Review by nima-karimi — CHANGES_REQUESTED** [review]
Thanks, @mikkamp. I just gave this a quick test run and noticed that there are a few places left unchanged. Mainly in the `\Automattic\WooCommerce\GoogleListingsAndAds\Vendor\Google\Auth\CredentialsLoader::makeHttpClient` method (file: `vendor/google/auth/src/CredentialsLoader.php`) where the `GuzzleHttp` classes are being used directly with FQN (and not a use statement). We should also replace any usages like this.

**Comment by mikkamp** [comment]
Thanks, for catching those. We actually use very little of Google\Auth since we swap out the auth header with our Jetpack token, and the WCS handles the actual authentication. But for completeness I can include those as well.

**Review by nima-karimi — APPROVED** [review]
Everything works as expected on my side and the code looks good to me. But since the changes here affect many functionalities, I think @layoutd can also give this PR a review and testing just to be sure.

**Comment by findingsimple** [comment]
@layoutd would love to try and get this wrapped today if we can and get the release out 🙇‍♂️

**Review by layoutd — APPROVED** [review]
👍🏻  Looks good, I've put the extension through its paces and haven't hit any snags.

**Pull request merged**
