### PR TITLE
Use Merchant Center service instead of a trait

### PR DESCRIPTION
**Pull request by nima-karimi**
### Changes proposed in this Pull Request:

Split from #319 

This PR replaces the `MerchantCenterTrait` with a new service called `MerchantCenterService`. This service covers all of the functionality of the said trait but it uses a constructor to retrieve the services it needs instead of depending on the class that uses it to provide those services. IMO this will make for a more testable and predictable code base. 

The service can be injected directly via the container or it can be inflected to classes that implement the `MerchantCenterAwareInterface` interface. A helper trait called `MerchantCenterAwareTrait` is also created to provide a `$merchant_center` property and a set method for classes that need this service (similar to the way `OptionsAwareInterface` and `OptionsAwareTrait` work).

### Detailed test instructions:

This change required some refactoring but most of the changes are only one line and mainly replace the usage of `MerchantCenterTrait`. It might be a good idea to just go through the basic flow of onboarding and then product syncing to see if everything is working.

### CODE REVIEW

**Review by JPry — CHANGES_REQUESTED** [review]
This mostly looks good. I think there are just a few minor things to address first.

**Review by JPry — APPROVED** [review]
I'm marking this approved pending the minor changes I mentioned previously.

**Review by mikkamp — COMMENTED** [review]
Generally it's looking good, but I did add a few comments on some things we might want to reconsider. I'm also getting a fatal error which stems from the commit that moved the disconnect function.

**Review by mikkamp — APPROVED** [review]
Thanks for those changes, it's working now without errors.

Although it seems the call to `disconnect_merchant` is now missing both from the service and the account controller, it will need to be added back to the account controller until we can refactor the code. I created an issue here for the refactor: https://github.com/woocommerce/google-listings-and-ads/issues/388

**Pull request merged**
