### PR TITLE
Multi-country targeting campaign - Move the free ads credit box to step 1 of ads account setup

### PR DESCRIPTION
**Pull request by eason9487**
### Changes proposed in this Pull Request:

This PR implemented the "Move the free ads credit box to step 1 of ads account setup" part of #1248:

- Move the free ads credit box to step 1 of ads account setup.
- Move the *free-ad-credit* folder and adjust its layout and style to fit with the visual design.

:warning: Some notes:
- It won't be shown on the single-page campaign creation/edit page. (Confirmed with Jill)
- The copies have been changed after https://github.com/woocommerce/google-listings-and-ads/pull/1217 and the updated copies should be the latest. So the copies in the box will be different between implementation and visual design.

### Screenshots:

https://user-images.githubusercontent.com/17420811/154460450-ce068338-8420-4f1a-8d99-8862bb53ecc8.mp4

### Detailed test instructions:

💡  If test with an unconnected account, it will encounter a bug that could be addressed by #1252. It will need to cherry-pick fix from #1252 on your local if want to test from an unconnected ads account. 🙏 

Or, since this PR hasn't changed any logic, it could be tested by simulating a connected Google ads account that fulfills the eligibility of free ads credit. To do so, add the following code snippet at [line 26 of useFreeAdCredit hook](https://github.com/woocommerce/google-listings-and-ads/blob/e396335223d453a1d0d4885ebb6c6a471fc5abee/js/src/hooks/useFreeAdCredit.js#L26).
```js
if ( googleAdsAccount?.status === 'connected' ) {
	return true;
}
```

1. Go to ads account setup: `/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fsetup-ads`
2. The free ads credit box should appear after Google ads account data is fetched and its status is connected.
3. Continue to step 2. There should be no free ads credit box anymore.
4. Go to the campaign creation/edit page. There should be no free ads credit box anymore.

### CODE REVIEW

**Comment by puntope** [comment]
❓ 

> The copies have been changed after https://github.com/woocommerce/google-listings-and-ads/pull/1217 and the updated copies should be the latest. So the copies in the box will be different between implementation and visual desing

Screenshot 2022-02-17 at 16 32 45

Based on #1217 . I see we removed the `<br>` between `checkLink` and `termsLink` I take as granted that this was discussed with the design team and we don't want to force the new line anymore.

**Comment by puntope** [comment]
💅 

Another consideration that came to my mind now is it would be better to have `free-ad-credit` component at the top level as possible (i.e in `setup-ads`) instead of locating the folder in any specific step. 

This together with implementing the hook `useFreeAdCredit` inside Free Ads returning null if false...  instead of using it as a condition outside the component.  

I know is very opinionated and out of scope but it just came to my mind after seeing we need to move the whole folder structure to move/show the component within different areas. Or even returning the component itself in the hook instead of a boolean.

**Review by puntope — COMMENTED** [review]
LGTM the behaviour. 

Just a question regarding the Terms Link to confirm before approval... and some thoughts (no need to change anything) regarding the location of `useFreeAds` and the `free-ads-folder`

**Comment by puntope** [comment]
❓ 

Sorry other question I dont understand.

> It won't be shown on the single-page campaign creation/edit page. (Confirmed with Jill)
> Go to the campaign creation/edit page. There should be no free ads credit box anymore.

Where is this one exactly?

**Comment by eason9487** [comment]
@puntope 

> ❓
> 
> > The copies have been changed after #1217 and the updated copies should be the latest. So the copies in the box will be different between implementation and visual desing
> 
> Screenshot 2022-02-17 at 16 32 45
> 
> Based on #1217 . I see we removed the \<br\> between `checkLink` and `termsLink` I take as granted that this was discussed with the design team and we don't want to force the new line anymore.

Sorry, I don't understand this comment. I checked the commits history of #1217, and I don't see any of them has ever changed the `<br>`. And I can't find relevant discussions about the new line between devs and the design team.

I removed the `<br>` by this PR was to align with the visual design of this project. I thought only the copies are outdated but the layout should be correct.

Could you provide more context?

**Comment by puntope** [comment]
> I removed the `<br>` by this PR was to align with the visual design of this project.

That is what I wanted to check. If this is actually the desired design (to have terms link inline, without a new line). In the previous PR https://github.com/woocommerce/google-listings-and-ads/pull/1217 I saw `<br>` was there so wondering which one is the correct. 

> Sorry, I don't understand this comment. I checked the commits history of https://github.com/woocommerce/google-listings-and-ads/pull/1217, and I don't see any of them has ever changed the <br>. And I can't find relevant discussions about the new line between devs and the design team.

Yes, my bad, the `<br>` was there (not added). I'm just confirming if this is a design decision.

**Comment by eason9487** [comment]
@puntope

> 💅
> 
> Another consideration that came to my mind now is it would be better to have `free-ad-credit` component at the top level as possible (i.e in `setup-ads`) instead of locating the folder in any specific step.
> 
> This together with implementing the hook `useFreeAdCredit` inside Free Ads returning null if false... instead of using it as a condition outside the component.

All files in the *setup-ads* folder are placed as close to the level where they are imported as possible, and I tend to follow the current way of placing them.

> I know is very opinionated and out of scope but it just came to my mind after seeing we need to move the whole folder structure to move/show the component within different areas. Or even returning the component itself in the hook instead of a boolean.

Yeah, it's a bit out of scope. I'd suggest adding your idea to #195. Although I don't know when we'll have the chance to reorganize frontend files, but at least we could gather a consensus on it first in the same follow-up issue.

**Comment by eason9487** [comment]
@puntope 

> ❓
> 
> Sorry other question I dont understand.
> 
> > It won't be shown on the single-page campaign creation/edit page. (Confirmed with Jill)
> > Go to the campaign creation/edit page. There should be no free ads credit box anymore.
> 
> Where is this one exactly?



The campaign creation page, which is a single page without a multi-step flow like the ads setup, can be found by clicking on the "Add paid campaign" button on the dashboard page.

And the campaign edit page can be found by clicking the "Edit" link on any of existing paid campaigns on the dashboard page and then clicking on the "Continue to edit" button on the popped-up modal.

Originally, the free ads credit box was inside the budget section, it should not appear in the above two places.

**Comment by eason9487** [comment]
@puntope 

> That is what I wanted to check. If this is actually the desired design (to have terms link inline, without a new line). In the previous PR #1217 I saw `<br>` was there so wondering which one is the correct.

> I'm just confirming if this is a design decision.

Got it. This part of layout was updated the last week, and I thought it was looked visually reasonable without that forced line break after moving terms link to the new place. So I didn't discuss this with the design team.

---

Hi @j111q 👋 

Originally, the terms link had a forced line break in code implementation. In the Figma of this project, there is no longer a line break between that link and the preceding text. I think @puntope wanted to confirm that is this actually the desired design?

Before
154430320-b99d4db2-ed72-4c57-88bb-5f07cf3e9c62

After

**Comment by puntope** [comment]
> Originally, the free ads credit box was inside the budget section, it should not appear in the above two places.

✅  Looks good

Screenshot 2022-02-18 at 11 26 07

Screenshot 2022-02-18 at 11 26 00

**Review by puntope — APPROVED** [review]
✅  LGTM

This PR could be merged after checking the `<br>` thing with the design team. 

I tested the expected behaviour as well as the code ... it looks good to me.

**Comment by eason9487** [comment]
> This PR could be merged after checking the `<br>` thing with the design team.

Since it is not available to confirm this these days and after checking with @puntope, I will proceed with PR merging as-is. And I will double-check https://github.com/woocommerce/google-listings-and-ads/pull/1253#issuecomment-1043812982 with @j111q and create another PR if it needs adjustment.

**Comment by j111q** [comment]
Hello! Sorry for the late reply, yes it's fine without the line break. Thank you for checking though!! 🙏

**Pull request merged**
