### PR TITLE
Add unit test configurations

### PR DESCRIPTION
**Pull request by nima-karimi**
### Changes proposed in this Pull Request:

This PR adds the basic configuration files for unit tests. Travis build configurations are also updated to run the unit tests.

A new command called `composer test-unit` is added to Composer that runs all of the unit tests. This script is run by Travis on every build.

To build our plugin I had to use `npm run dev` to only build the front-end files. I would much prefer to run the tests on a production build. However, our build scripts remove unnecessary `vendor` files including `phpunit` and other dev libraries required for the tests to run. I think we would need to do our builds in a temporary folder (similar to `woorelease`) and don't delete anything from the project files. But that's probably the subject of another PR.

(Replacing my previous PR https://github.com/woocommerce/google-listings-and-ads/pull/824 here because it was used to test Travis and had a lot of unnecessary commits)

### Detailed test instructions:

1. Run `vendor/bin/phpunit` and confirm that the tests run successfully
2. Confirm that all of the Travis builds for this PR pass and include the unit tests

**Todo:**
- [x] Add docs to readme for setting up and running the unit tests

### CODE REVIEW

**Comment by nima-karimi** [comment]
For some reason, Travis doesn't trigger a build for this PR. The Travis config is correct because I just created a branch off of this one (`feature/test-travis-build`) and the builds were triggered for it:  https://travis-ci.com/github/woocommerce/google-listings-and-ads/builds/230833966

**Comment by mikkamp** [comment]
> To build our plugin I had to use npm run dev to only build the front-end files. I would much prefer to run the tests on a production build. However, our build scripts remove unnecessary vendor files including phpunit and other dev libraries required for the tests to run.

WooRelease sort of claims `npm run build` to build a full release of the plugin (which includes generating a pot and building a zip file). So we might be better off building the scripts in a separate command, something like this:

```
"build": "npm run build:scripts && npm run i18n",
"build:scripts": "NODE_ENV=production wp-scripts build",
```

**Comment by mikkamp** [comment]
Can you clarify which steps are needed to setup the unit tests to run them locally?

I created an empty database and then ran the command:
```
bin/install-wp-tests.sh gla_test <dbuser> <dbpass>
```

When I run the tests they all pass, but I do get an error before it completes installing WooCommerce:
```
$ vendor/bin/phpunit
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
WordPress database error Table 'gla_test.wptests_wc_webhooks' doesn't exist for query SELECT webhook_id
                                FROM wptests_wc_webhooks
                                WHERE 1=1
                                AND `status` = 'active'





                                ORDER BY webhook_id DESC made by PHPUnit\TextUI\Command::main, PHPUnit\TextUI\Command->run, PHPUnit\TextUI\Command->handleArguments, PHPUnit\TextUI\Command->handleBootstrap, PHPUnit\Util\FileLoader::checkAndLoad, PHPUnit\Util\FileLoader::load, include_once('/home/mik/woosites/woo-google/wp-content/plugins/google-listings-and-ads/tests/bootstrap.php'), require('/tmp/wordpress-tests-lib/includes/bootstrap.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WooCommerce->init, WooCommerce->load_webhooks, wc_load_webhooks, WC_Data_Store->__call, WC_Webhook_Data_Store->get_webhooks_ids, WC_Webhook_Data_Store->search_webhooks
<div id="error"><p class="wpdberror"><strong>WordPress database error:</strong> [Table &#039;gla_test.wptests_wc_webhooks&#039; doesn&#039;t exist]<br /><code>SELECT webhook_id
                                FROM wptests_wc_webhooks
                                WHERE 1=1
                                AND `status` = &#039;active&#039;





                                ORDER BY webhook_id DESC</code></p></div>WordPress database error Table 'gla_test.wptests_woocommerce_attribute_taxonomies' doesn't exist for query SELECT * FROM wptests_woocommerce_attribute_taxonomies WHERE attribute_name != '' ORDER BY attribute_name ASC; made by PHPUnit\TextUI\Command::main, PHPUnit\TextUI\Command->run, PHPUnit\TextUI\Command->handleArguments, PHPUnit\TextUI\Command->handleBootstrap, PHPUnit\Util\FileLoader::checkAndLoad, PHPUnit\Util\FileLoader::load, include_once('/home/mik/woosites/woo-google/wp-content/plugins/google-listings-and-ads/tests/bootstrap.php'), require('/tmp/wordpress-tests-lib/includes/bootstrap.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Post_Types::register_taxonomies, wc_get_attribute_taxonomies
<div id="error"><p class="wpdberror"><strong>WordPress database error:</strong> [Table &#039;gla_test.wptests_woocommerce_attribute_taxonomies&#039; doesn&#039;t exist]<br /><code>SELECT * FROM wptests_woocommerce_attribute_taxonomies WHERE attribute_name != &#039;&#039; ORDER BY attribute_name ASC;</code></p></div>Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. To execute these, use --group external-http.
Installing WooCommerce...
WooCommerce installed!
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

....                                                                4 / 4 (100%)

Time: 9.1 seconds, Memory: 60.50 MB

OK (4 tests, 6 assertions)
```

Is there anything I'm missing (the errors only show up on the first run)?

**Comment by nima-karimi** [comment]
> WooRelease sort of claims `npm run build` to build a full release of the plugin (which includes generating a pot and building a zip file). So we might be better off building the scripts in a separate command, something like this:
> 
> ```
> "build": "npm run build:scripts && npm run i18n",
> "build:scripts": "NODE_ENV=production wp-scripts build",
> ```

Hmm. This script would only have the front-end part built as production env right? 

I'm thinking we can run the whole build as usual but install `phpunit` and `phpcs` packages globally in Travis. I would prefer to test the build as we ship it to users (so that the tests could catch if, for example, we accidentally remove a vital package).

**Comment by mikkamp** [comment]
> This script would only have the front-end part built as production env right?

Yes, it would be the equivalent of running `npm run dev` but then for production.

The reason why I suggested a partial build is because generating the pot file can take up quite a bit of resources, but if we aren't worried about that then we can do a full build. Although if you fully want to test as shipped to users then you would need to generate the zip file and then install from that zip file.

**Comment by nima-karimi** [comment]
> The reason why I suggested a partial build is because generating the pot file can take up quite a bit of resources, but if we aren't worried about that then we can do a full build. Although if you fully want to test as shipped to users then you would need to generate the zip file and then install from that zip file.

Yeah, the resource usage could be an issue. Especially since it'll mean our tests will take longer. It's probably best to leave this part for the end-to-end tests to handle.

**Comment by nima-karimi** [comment]
> When I run the tests they all pass, but I do get an error before it completes installing WooCommerce

This issue is now resolved with https://github.com/woocommerce/google-listings-and-ads/pull/828/commits/d3e32f0ffac4b430c8a98ce4fdc1c2356c346848

The WooCommerce installation part was being run prematurely. It's now done after `setup_theme` action is called.

**Comment by nima-karimi** [comment]
Added the documentation for setting up the unit tests in https://github.com/woocommerce/google-listings-and-ads/pull/828/commits/7d5af45eb566b7e7774c6f25e9b2aff8eb593204.

@mikkamp Ready for another review.

Edit: Travis builds are running 🎉

**Review by mikkamp — APPROVED** [review]
Looks good all the tests pass and the install instructions work for me:
```
Time: 6.83 seconds, Memory: 60.50 MB

OK (4 tests, 6 assertions)
```

Are we going to be creating a followup issue to look into getting the tests running on PHP8? PHP7.4 is only in active support for another 4 months.

**Comment by nima-karimi** [comment]
Thanks for the review @mikkamp . Created this issue to track PHP 8 support: https://github.com/woocommerce/google-listings-and-ads/issues/850

**Pull request merged**
