### PR TITLE
API PULL - Validate MC connection in notifications

### PR DESCRIPTION
**Pull request by puntope**
### Changes proposed in this Pull Request:

Follow up for https://github.com/woocommerce/google-listings-and-ads/pull/2326#discussion_r1535416044

This PR introduces a check for MC Connection in the NotificationService class before the notify() is sent.

### Detailed test instructions:

0. Enable Notifications with the `woocommerce_gla_notifications_enabled` filter
1. With a connected MC - Go to the Connection test 
2. Try the Notify function and see it worked
3. Disconnect MC
4. Try the Notify function
5. See it failed
6. Go to the logs and see the entry generated by the failure.

### CODE REVIEW

**Comment by puntope** [comment]
UNit test not running due a problem with the API for getting the plugin versions. Seems not related to this PR.

**Review by jorgemd24 — APPROVED** [review]
Thanks @puntope for adding this!  It works well 👍 

Do you want to merge this to `feature/google-api-project` or [add/grant-access-to-google-wpcom-app-in-setting-page](https://github.com/woocommerce/google-listings-and-ads/tree/add/grant-access-to-google-wpcom-app-in-setting-page), mainly because the other changes that you did are merged in `grant-access-to-google-wpcom-app-in-setting-page`

**Comment by puntope** [comment]
> mainly because the other changes that you did are merged in grant-access-to-google-wpcom-app-in-setting-page

I did it in the main PR because I'm not using any function or service from the `grant-access-to-google-wpcom-app-in-setting-page` PR. 

Do you think I should merge it in `grant-access-to-google-wpcom-app-in-setting-page` PR.  instead?

**Comment by jorgemd24** [comment]
Hi @puntope, thanks for the clarification, actually I think it is better to merge it to `feature/google-api-project` so it is easier to review https://github.com/woocommerce/google-listings-and-ads/pull/2311

**Pull request merged**
