### PR TITLE
Add `admin-e2e-tests`

### PR DESCRIPTION
**Pull request by tomalec**
### Changes proposed in this Pull Request:

Add `admin-e2e-tests`
to make sure our plugin does not break WooCommerce Admin.
Add `@woocommerce/admin-e2e-tests` dependency,
clone test suites from https://github.com/woocommerce/woocommerce/tree/trunk/tests/e2e/specs as suggested in the release post (pcShBQ-6A-p2).

It seems valuable, as we actually fail on two:
```
 FAIL  ../../../tests/e2e/specs/wc-admin/admin-analytics/analytics-overview.test.js (37.502s)
  Analytics pages
    ✓ a user should see 3 sections by default - Performance, Charts, and Leaderboards (157ms)
    ✓ should allow a user to remove a section (248ms)
    ✓ should allow a user to add a section back in (199ms)
    moving sections
      ✕ should not display move up for the top, or move down for the bottom section (95ms)
      ✕ should allow a user to move a section down (30012ms)
      ✕ should allow a user to move a section up (203ms)
```

### Screenshots:

image

### Detailed test instructions:

1. Checkout this branch
2. ```sh
 	npm i
	npm run docker:up
	npm run test:e2e
	```


<!--
Optional.
Enter a summary of all changes in this Pull Request, which will be added to the changelog if accepted.
Each line should start with `(Fix|Add|Tweak|Update) - `, for example:
> Fix - I took care of something that wasn't working.
> Add - I added something new that's pretty cool.
> Tweak - I made a small change.
> Update - I made big changes to something that wasn't broken.

Leave the "Changelog entry" header in place completely empty, without any summary if no changelog entry is needed.
If you remove the "Changelog entry" header, the title of Pull Request will be used as the changelog entry.
-->
### Changelog entry

> Add - WooCommerce Admin tests suite.

### CODE REVIEW

**Comment by tomalec** [comment]
The tests fail due to [`admin-e2e` expecting "Mode down"](https://github.com/woocommerce/woocommerce-admin/blob/main/packages/admin-e2e-tests/src/specs/analytics/analytics-overview.ts#L65) but [get "Move **D**own"](https://github.com/woocommerce/woocommerce-admin/commit/f2a5d9143517333965ae5c48a6de4ae800ceb500#diff-57e0957b8abee06cb9ef3f13ca94b8d7c19897828d8f73cf42b2ed653a9cb0c6L71), so it seems to be another dependency version mismatch.

**Review by rrennick — APPROVED** [review]
@tomalec This looks fine to me. They tested great locally. We have an issue to investigate why [the analytics overview tests fail in some Mac environments](https://github.com/woocommerce/woocommerce/issues/30581).

```
  Analytics pages
    ✓ a user should see 3 sections by default - Performance, Charts, and Leaderboards (110ms)
    ✓ should allow a user to remove a section (153ms)
    ✕ should allow a user to add a section back in (548ms)
    moving sections
      ✓ should not display move up for the top, or move down for the bottom section (139ms)
      ✕ should allow a user to move a section down (521ms)
      ✕ should allow a user to move a section up (30011ms)
```

**Comment by tomalec** [comment]
Thank you @rrennick !

----

Now, there is a question for the Woogle team. Those tests require 5.6, but we are [quite behind](https://github.com/woocommerce/google-listings-and-ads/blob/develop/google-listings-and-ads.php#L14-L15):
```md
 * WC requires at least: 5.2
 * WC tested up to: 5.5
``` 
- Do we want to merge it?
- Do we want to skip failing ones or keep them failing? - They are simply failing due to the older version of WC, so there is nothing actionable on our end.

Currently, we are not running E2E on CI, so broken tests would not block anything.

**Comment by ecgan** [comment]
> we are [quite behind](https://github.com/woocommerce/google-listings-and-ads/blob/develop/google-listings-and-ads.php?rgh-link-date=2021-08-31T21%3A44%3A18Z#L14-L15):

I think we would need to test and bump it up one day. Latest version of WooCommerce is [5.6.0](https://github.com/woocommerce/woocommerce/releases/tag/5.6.0) released about two weeks ago, so we should bump it to the following ("at least" version is L-2):

> ```lisp
>  * WC requires at least: 5.4
>  * WC tested up to: 5.6
> ```

---

> Those tests require 5.6...
> * Do we want to merge it?

I think we would need to take the "lowest common denominator" approach (see previous related Slack thread in our team channel p1629975717010800/1629914514.272300-slack-CK365S85V) and make sure things work with L-2 version, so we probably shouldn't merge it now, but later when "at least" version becomes 5.6.0.

**Comment by tomalec** [comment]
> I think we would need to take the "lowest common denominator" approach (see previous related Slack thread in our team channel p1629975717010800/1629914514.272300-slack-CK365S85V) and make sure things work with L-2 version, so we probably shouldn't merge it now, but later when "at least" version becomes 5.6.0.

I find it funky. 
As I've seen `admin-e2e-tests` a way to check:
- whether our plugin does not break the core WC features
- whether we are compatible with the given version of WC

And from the results of the tests, you can tell, that we did not break a thing, and our plugin is compatible with 5.6, but we cannot use it before we bump our minimal version to `5.6`. As what they check:
- whether the minimal WC version used by our plugin is compatible with the tests for the latest version of WC - which is not, as there was a small change in WC.


-----

It would be nice to have a package that once used would run the tests for a WC version against that version of WC.

**Comment by tomalec** [comment]
This PR, grown old, and rotten a bit, I'll try to redo it on the latest `develop`.
Plus, given https://github.com/facebook/jest/issues/11781 is fixed, now I'd try to make it so we will run the test from node_modules directly, without the need for duplication, and wrapping increasing the risk of timeout.

**Comment by mikkamp** [comment]
Our E2E tests no longer rely on the packages from WooCommerce as they are deprecated. We use wp-env now, see PR #2030
So I'm closing this PR.

**Pull request closed without merging**
