### PR TITLE
Externalize all `@woocommerce` packages via DEWP and remove the selective bundling implementation

### LINKED ISSUE #1527: Review bundled `@woocommerce/*` dependencies
_This is a follow-up from https://github.com/woocommerce/google-listings-and-ads/pull/1526_

### Describe the bug:

After [switching to `@woocommerce/dependency-extraction-webpack-plugin`](https://github.com/woocommerce/google-listings-and-ads/pull/1526) it turned out we are bundling the following WooCommerce dependencies instead of using the versions shipped with WC:
   - `@woocommerce/currency`
   - `@woocommerce/date`
   - `@woocommerce/number`
   - `@woocommerce/tracks`
I don't recall any reason to consciously bundle our own versions. In the long run it's better to reuse what's given by the platform.

I think it would be safer to address this issue in a cooldown period, to avoid unexpected bugs popping somewhere.

### Steps to reproduce:

1. `npm i && npm run build`
2. Open `js/build/index.js`
3. Search for `@woocommerce/`

### Expected behavior:

There should be no results unless there is a specified good reason.

### Actual behavior:

4 packages are bundled

### LINKED ISSUE #1971: `moment.tz` gets conflicted when the site timezone is other than UTC
### Describe the bug:

WordPress loads a moment.js script that already contains the code for `moment.tz`, and the `WP` timezone is initialized by `@wordpress/date`.

However, `@woocommerce/date` may overwrite the global `moment.tz` because it imports [moment-timezone](https://github.com/woocommerce/woocommerce/blob/7.6.0/packages/js/date/src/index.ts), causing the above `WP` timezone to be lost and then the conflict.

Since `@woocommerce/date` is DEWPed In GLA, it always has this conflict in all GLA admin react-powered pages. This conflict doesn't seem to have caused any real errors yet because GLA doesn't use any relevant `@wordpress/date` functions. Therefore, this GH issue is mainly used to follow up on potential problems.

### Steps to reproduce:

1. Change the site timezone to GMT+X, X > 0
2. Go to any GLA admin page
3. Open the Console tab of browser DevTool
4. Run `wp.date.getDate()` or `moment.tz('2023-05-01T18:00:00', 'WP')`

### Expected behavior:

`moment.tz` should have only one code implementation and be initialized once.

### Actual behavior:

`moment.tz` gets conflicted when the site timezone is other than UTC

### PR DESCRIPTION
**Pull request by eason9487**
### Changes proposed in this Pull Request:

Closes #1527
Closes #1971

This PR externalizes all `@woocommerce` packages via DEWP, and it can also fix #1971 by the way.

- Change the bundled `@woocommerce` packages to use external sources from DEWP.
   - `@woocommerce/currency`
   - `@woocommerce/date`
   - `@woocommerce/number`
   - `@woocommerce/tracks`
- Remove the selective bundling implementation that gradually externalizes packages into DEWP.
- Rebalance the max size config of bundlewatch for each non-wildcard file to 1.2 times.
- Update DEWP document.

### Screenshots:

image

### Detailed test instructions:

1. Check if all build scripts, `npm start`, `npm run dev`, `npm run start:hot` and `npm run build`, can run successfully.
2. Run bundle analyzer: `npm run env -- NODE_ENV=production wp-scripts build --webpack-bundle-analyzer`
   - Check if there is no DEWPable `@woocommerce/*` package included in the build bundle.
3. Read through [Selective bundling & extracting](https://github.com/woocommerce/google-listings-and-ads/blob/6358de365713ede2013f4edae6d2d680ead09f3e/Working%20with%20DEWP.md#selective-bundling--extracting) to see if the updated description is appropriate.
4. Follow the reproduction steps in #1971 to check if `wp.date.getDate()` can run successfully.

### Additional details:

The [current versions](https://github.com/woocommerce/google-listings-and-ads/blob/6358de365713ede2013f4edae6d2d680ead09f3e/package.json#L22-L28) of `@woocommerce/currency`, `@woocommerce/date`, `@woocommerce/number` and `@woocommerce/tracks` packages are the same versions as the latest WooCoomerce release (8.0.2):
- https://github.com/woocommerce/woocommerce/blob/8.0.2/packages/js/currency/CHANGELOG.md
- https://github.com/woocommerce/woocommerce/blob/8.0.2/packages/js/date/CHANGELOG.md
- https://github.com/woocommerce/woocommerce/blob/8.0.2/packages/js/number/CHANGELOG.md
- https://github.com/woocommerce/woocommerce/blob/8.0.2/packages/js/tracks/CHANGELOG.md

Therefore, switching to DEWP should not have any effect.

### Changelog entry

> Dev - Externalize all WooCommerce JavaScript packages via Dependency Extraction Webpack Plugin (DEWP) and remove the selective bundling implementation that gradually externalizes packages into DEWP.

### CODE REVIEW

**Comment by tomalec** [comment]
> The [current versions](https://github.com/woocommerce/google-listings-and-ads/blob/6358de365713ede2013f4edae6d2d680ead09f3e/package.json#L22-L28) of `@woocommerce/currency`, `@woocommerce/date`, `@woocommerce/number` and `@woocommerce/tracks` packages are the same versions as the latest WooCoomerce release (8.0.2):


:+1: They also stay at those versions since our L-2 7.8.2:
```
 dewped pdep --wpVersion=6.2.2 --wcVersion=7.8.2 -d .externalized.json
 ›   Warning: @woocommerce/settings version not found in WooCommerce 7.8.2 at 
 ›   https://raw.githubusercontent.com/woocommerce/woocommerce/7.8.2/packages/js/settings/package.json.
 Name                               WordPress 6.2.2 WooCommerce 7.8.2 Local    
 ────────────────────────────────── ─────────────── ───────────────── ──────── 
 @woocommerce/components                            12.0.0            ^10.3.0  
 @woocommerce/currency                              4.2.0             ^4.2.0   
 @woocommerce/customer-effort-score                 2.2.0             ^2.2.0   
 @woocommerce/data                                  4.1.0             ^4.1.0   
 @woocommerce/date                                  4.2.0             ^4.2.0   
 @woocommerce/navigation                            8.1.0             8.1.0    
 @woocommerce/number                                2.4.0             ^2.4.0   
 @woocommerce/settings                              unknown                    
 @woocommerce/tracks                                1.3.0             ^1.3.0   
```

Maybe we could consider (not necessarily here) bumping `@woocommerce/components` to `12.0.0`

**Comment by tomalec** [comment]
I'm not a native English speaker, but I passed `.md` section through Grammarly and added a few tweaks, WDYT of the below:
```md
In the past, we did bundle some packages provided by WordPress/WooCommerce instances. We did so to use a specific package version, for example, to ship a new feature we need, fix, or avoid a bug. However, bundling a package tends to introduce other errors, as some packages are not effectively modular, so we face version conflicts, style collisions, etc.
Also, we'd like to reduce the size of our bundle, so eventually, we aim to extract/externalize as much as possible and import from an external package when possible.

To help with that, we had implemented the `extracted/` prefix in the past. It was also a custom implementation in [`webpack.config.js`](webpack.config.js).
Thanks to that, even though a package is bundled, the given import would fetch it from external.

Now, we have already externalized all DEWP-able packages, so we also removed the implementation of the `extracted/` prefix.
If someday we ever need it again, please refer to:
- The PR implemented it: https://github.com/woocommerce/google-listings-and-ads/pull/1762
- The commit removed it: https://github.com/woocommerce/google-listings-and-ads/commit/5a2e20409a53ccb3b7fcbfe5c46988ca2b153b38
Alternatively, we can consider an opposite approach and selectively **bundle** with a similar prefix implementation.
```

**Review by tomalec — APPROVED** [review]
Reviewed the code, tested the build scripts, smoke tested the site, LGTM.

Thank you for such a significant cleanup :) and removing w big chunk from our bundle 
image

**Comment by eason9487** [comment]
Thanks for the review, @tomalec 

> > The [current versions](https://github.com/woocommerce/google-listings-and-ads/blob/6358de365713ede2013f4edae6d2d680ead09f3e/package.json#L22-L28) of `@woocommerce/currency`, `@woocommerce/date`, `@woocommerce/number` and `@woocommerce/tracks` packages are the same versions as the latest WooCoomerce release (8.0.2):
> 
> 👍 They also stay at those versions since our L-2 7.8.2:
> [...]
> Maybe we could consider (not necessarily here) bumping `@woocommerce/components` to `12.0.0`

I tried bumping the WP and WC packages to L-2 while working on #2069, but there were quite a few problems with `npm install`, so more time is needed for further investigation. I'll revisit this some other time.

> I'm not a native English speaker, but I passed `.md` section through Grammarly and added a few tweaks, WDYT of the below: [...]

Thanks for the suggestion! Updated in https://github.com/woocommerce/google-listings-and-ads/pull/2072/commits/0157e872b1d288a503b49ba919aa101695e8e574.

**Pull request merged**
