### PR TITLE
Add packages to allow-plugins directive and update lock file

### PR DESCRIPTION
**Pull request by JPry**
### Changes proposed in this Pull Request:

Composer has a new [`allow-plugins`](https://getcomposer.org/doc/06-config.md#allow-plugins) setting for the `config` property to allow for specifying trusted (or untrusted) plugins from packages. This PR specifies the trusted plugins for this project.

```
automattic/jetpack-autoloader contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "automattic/jetpack-autoloader" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] y

dealerdirect/phpcodesniffer-composer-installer contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "dealerdirect/phpcodesniffer-composer-installer" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] y
```

### Detailed test instructions:

1. Run `composer install` from `develop` using Composer 2.2.0+, and observe the messages above
2. Run `composer install` from this branch and observe no messages, and the plugins are installed

### Changelog entry

> Dev – Update composer trusted plugins

### CODE REVIEW

**Comment by mikkamp** [comment]
@JPry Just linking some reasoning on why it's failing p1641973298070000/1641945030.068000-slack-CK365S85V

Was it the intention to update `guzzlehttp/psr7` in the lock file from version 1.8.2 > 2.1.0?

We have issue #1186 for updating the Ads library, maybe we can create another one for the content API library, looks like we'll need at least version [2.11.0](https://github.com/googleapis/google-api-php-client/releases) to use `guzzlehttp/psr7` v2.

**Comment by mikkamp** [comment]
Created issue for updating the Google API library #1199

**Comment by mikkamp** [comment]
In my opinion we need to be a bit careful with merging this change. The test instructions for this PR mentions to confirm that there are no longer any plugin-allow messages. But the composer.lock file is also updating all the packages to the latest allowed versions. I think it's great to be updating all of those, but our unit test don't cover them fully, so I wouldn't feel comfortable updating without some additional smoke tests.

Seems there are still Google packages that are being updated after #1204 (since there have been new releases since then).

Some notable ones I found are:

```
google/common-protos 1.4.0 > 2.0.0 (major version bump)
google/gax v1.10.0 > v1.11.4

automattic/jetpack-connection v1.24.0 > v1.36.1
```

I think with those updates we should at least be testing the following:
- Jetpack connect / disconnect
- Basic requests to the Content API (Merchant Center)
- Basic requests to the Ads API

Another alternative would be to only update the composer.json file and leave the package updates for a PR where we fully test the updated packages.

**Comment by JPry** [comment]
Based on the issues mentioned by @mikkamp above, I decided to redo this without the additional package updates. Closing this in favor of #1235

**Pull request closed without merging**
