### PR TITLE
Display the budget currency that will actually be used.

### PR DESCRIPTION
**Pull request by tomalec**
### Changes proposed in this Pull Request:

- Request budget recommendation in Ads account's currency,
instead of store's currency. The user provides the amount in Ads currency which is fixed and unchangeable, therefore the recommendation should be given in the same one.

Solves part of https://github.com/woocommerce/google-listings-and-ads/issues/363#issuecomment-883081178

##### Shop currency
image

#### Ads currency 
image

##### Budget recommendation currency
image
currency

### Detailed test instructions:

1. Set the store currency to _X_ (PLN)
2. Setup Ads account
3. Change the store currency to _Y_ (EUR)
4. Create a new campaign ([`/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fdashboard&subpath=%2Fcampaigns%2Fcreate`](https://gla1.test/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fdashboard&subpath=%2Fcampaigns%2Fcreate) )
5. You should see the budget input and recommendation requested and displayed in the Ads account currency _X_ - the one that will be used after clicking "Launch paid campaign". The one visible at https://ads.google.com/aw/campaigns? 

### Changelog entry

> Fix - display the correct currency actually used for the paid campaign budget.

### Additional notes:
1. Even though the Ads currency code is displayed, the ** store's currency formatting settings** (thousand & decimal delimiters, etc.) are being used.
2. We end up with the blink of no country code in the input. This is due to the number of requests we make for displaying the page. Browsers limit the number of concurrent requests, so this one gets significantly delayed. @j111q is that acceptable? We may try to find some ways to work around it by pre-loading this data before displaying the countries list.
3. There still are a number of things to improve around Ads currency, I'll address them in separate PRs:
	1. Show a warning that the store and Ads currencies differ.
	2. Fix the currency displayed in the Dashboard.

### CODE REVIEW

**Comment by tomalec** [comment]
@mikkamp, @layoutd, I'd appreciate your comment on https://github.com/woocommerce/google-listings-and-ads/pull/901/files#diff-b2b05ecdb223afb6bca1aeffc44a39a28c53535c81307f51ca4fee632ae6c416R68-R70
I'm not sure if it's 
- a kosher PHP way to implement that
- the safest to use a currency from options, and assume it's already there. 
	I was thinking of adding a `get_ads_currency` function to `src/API/Google/Proxy.php`, like https://github.com/woocommerce/google-listings-and-ads/pull/795/files#diff-6df15bc3808d9d330de42aaea4dec5f939e2fdd880181689b417680814f6a448R369-R372, then using it here. But using the Proxy methods here was beyond my PHP monkey-coding skills :speak_no_evil:

**Comment by mikkamp** [comment]
I think we should try and get it from the Proxy class (or possible AdsService) because if the user onboarded using an older version and then tried creating a campaign it might not have the currency saved (so we would need to trigger a request to the API). I can put up a PR that resolves that, or would you like me to add a commit to this one?

Also just a side note: we have `BaseOptionsController`, so it would have been easier to extend from this class instead of implementing the `OptionsAwareInterface`

**Comment by tomalec** [comment]
Thank you @mikkamp for the support and adding commits here :)

**Comment by tomalec** [comment]
Just noticed that the Ads account is delayed not because of browser piping requests, but because it's put into the sequence after the google account request.
https://github.com/woocommerce/google-listings-and-ads/blob/trunk/js/src/hooks/useGoogleAdsAccount.js#L26-L31

@ecgan Do you remember why is it so? We don't need any Google account id to request solely for Ads account.

Is that because for some other request instead of just `useGoogleAdsAccount` we need rather `useAllAccountsSetUpForAddingCampaign`

(:scroll: If we are about to change something in that area, that could be addressed in a separate PR, as this may be beneficial for other PRs, and  such a change would require revisiting a number of other flows)

**Comment by ecgan** [comment]
@tomalec ,

> Just noticed that the Ads account is delayed not because of browser piping requests, but because it's put into the sequence after the google account request.
> [`trunk`/js/src/hooks/useGoogleAdsAccount.js#L26-L31](https://github.com/woocommerce/google-listings-and-ads/blob/trunk/js/src/hooks/useGoogleAdsAccount.js#L26-L31)
> 
> @ecgan Do you remember why is it so? We don't need any Google account id to request solely for Ads account.

I think the idea is that when Google account is not connected, we would automatically assume Google Ads account is not connected and we do not make API calls to get the Google Ads account info. If we do make API calls, the API would throw error. 

The sequential API calls is done in this manner, IIRC:

- For Google Merchant Center: check for Jetpack -> check for Google account -> check for Google Merchant Center account.
- For Google Ads account: check for Jetpack -> check for Google account -> check for Google Ads account.

See the related team slack thread discussion, between me, @mikkamp and @layoutd : p1613651181432800/1613643321.423600-slack-CK365S85V. 

Another related PR comment: https://github.com/woocommerce/google-listings-and-ads/pull/217#issuecomment-781547028

There may be other discussions in other places that I haven't found.

**Comment by tomalec** [comment]
Thanks for the detailed and elaborate explanations. From what it seems, I'd leave it as is here. Then create another issue, to potentially improve it here or there.

**Review by eason9487 — APPROVED** [review]
LGTM.

**Pull request merged**
