### PR TITLE
Update min. WC version to 5.7 (L-2).

### PR DESCRIPTION
**Pull request by tomalec**
### Changes proposed in this Pull Request:

This PR catch up a little with our L-2 policy in regards to WooCommerce.
It bumps the min version and updates a few externalized dependencies.

[WC `5.7.1` uses WC-admin`@2.6.5`](https://github.com/woocommerce/woocommerce/blob/5.7.1/composer.json#L24)

Which uses 

- components 8.0.0+ [https://github.com/woocommerce/woocommerce-admin/blob/v2.6.5/packages/components/package.json#L3](https://github.com/woocommerce/woocommerce-admin/blob/v2.6.5/packages/components/package.json#L3)
	**but** `8.0.0` was not released to npm so  we'll fall down to `7.1.0`
- data 1.4.0+ [https://github.com/woocommerce/woocommerce-admin/blob/v2.6.5/packages/data/package.json#L3](https://github.com/woocommerce/woocommerce-admin/blob/v2.6.5/packages/data/package.json#L3)
- navigation 6.1.0+ [https://github.com/woocommerce/woocommerce-admin/blob/v2.6.5/packages/navigation/package.json#L3](https://github.com/woocommerce/woocommerce-admin/blob/v2.6.5/packages/navigation/package.json#L3)

The above should not affect the actual plugin, as those packages are not included in the bundle (they are externalized via DEWP)

This PR also bumps `@woocommerce/date` to fix unit tests. Unfortunately, this is the only change that may affect the actual runtime, as the `/date` package is the only which is not externalized.

### Screenshots:

image

### Detailed test instructions:

1. `npm run dev`
2. `npm run test-unit`
3. `npm run docker:up`
4. `npm run test:e2e`
5. Click through the plugin, to look for any regressions issues introduced by updating the `/date` package :|

### Additional notes:
1. For the externalized dependencies, I start to use `--save-exact` to make them stand out a little in `package.json`, and make sure we are really testing the version actually shipped with WCx.y. WDYT of adding this convention to our repo/team guidelines?
2. I'd create separate PRs for
	1. Extracting `/date` via DEWP
	2. Removing the `external-components` that are no longer needed.

### Changelog entry

> Update - min. WC version to 5.7

### CODE REVIEW

**Comment by tomalec** [comment]
Failing `tests/unit/wc-admin-dependency.test.js` seems like another incarnation of https://github.com/woocommerce/woocommerce-admin/issues/6483

**Comment by tomalec** [comment]
Thanks @eason9487 updating `@woocommerce/date` helped :tada:

**Comment by tomalec** [comment]
//cc @puntope if you would like to automate this process, we may consider adding [`maybe_bump_requires_at_least` in `woorelease`](https://github.com/woocommerce/woorelease/blob/develop/includes/tools/class-version-bump.php#L31)
but then to meet DEWP-inducted needs we would need to run `wp-scripts packages-update` with my change from https://github.com/WordPress/gutenberg/pull/36005, plus Woo-equivalent to do the same for `@woocommerce/*`

Then we could centralize the source of min.WP/WC version, for PHP code, CI, READMEs, etc.

**Comment by puntope** [comment]
> to run `wp-scripts packages-update` with my change

Nice, After looking at it, I understand that the feature fetches the WP version from the repo.

> we may consider adding [`maybe_bump_requires_at_least` in `woorelease`](https://github.com/woocommerce/pinterest-for-woocommerce/blob/update/npm-scripts/package.json#L101-L117) 

I see the link points to npm scripts but I'm unsure what we need to add and why. Could you elaborate? 

>  to meet DEWP-inducted needs

What do you mean by this?


> plus Woo-equivalent to do the same for `@woocommerce/*`

Do you mean that we would need also to merge your changes[ regarding this](https://github.com/WordPress/gutenberg/pull/36005) in the WooCommerce repo?

> Then we could centralize the source of min.WP/WC version, for PHP code, CI, READMEs, etc.

Let's do it, I'm in

**Comment by puntope** [comment]
* So far unit test went well ✅ 
* Overview of files looks good for me ✅ 
* WIP Testing with e2e
* WIP Testing the plugin manually (tomorrow I'm planning to spend my whole day on testing for WP Compat so, perfect)

💅 

> 1. I start to use `--save-exact` to make them stand out a little in `package.json`, and make sure we are really testing the version actually shipped with WCx.y. WDYT of adding this convention to our repo/team guidelines?

`npm config set save-exact true` could work as well. (Just saw it on a website investigating why is good to have --save-exact xD).  For me adding exact deps sound safer in our context. 👌 


❓ ❓ ❓ ❓ ❓ 

 > The above should not affect the actual plugin, as those packages are not included in the bundle (they are externalized via DEWP) This PR also bumps @woocommerce/date to fix unit tests. Unfortunately, this is the only change that may affect the actual runtime, as the /date package is the only which is not externalized.
 
 I think I'm having some gaps in understanding the difference between externalized dependencies with DEWP and other dependencies like could be  `@woocommerce/navigation`??? 
 
 Also, I don't understand why "@woocommerce/date": "^3.1.0" is with ^ and then "@woocommerce/navigation": "6.1.0" without it. I understood that idea was to use exact deps. 
 

 > npm run test:e2e
 
 I'm getting `Waiting for testing environment` after starting my e2e , but I guess is not well configured on my side. Will check asap.

**Comment by tomalec** [comment]
> > we may consider adding maybe_bump_requires_at_least in woorelease
>
> I see the link points to npm scripts but I'm unsure what we need to add and why. Could you elaborate?

Sorry, the wrong link, I meant to link to woorelease `Version_Bump`'s `maybe_bump_tested` code https://github.com/woocommerce/woorelease/blob/develop/includes/tools/class-version-bump.php#L31

> > to meet DEWP-inducted needs
>
> What do you mean by this?

https://github.com/WordPress/gutenberg/issues/35630

in short:

If we use DEWP (Dependency Extraction Webpack Plugin) some packages we import, like `@woocommerce/components` are not bundled, and in runtime, they are fetched from WP instance running the plugin. So technically, we do not need to `npm install` them, keep in `package.json` etc. 

But we do install them locally, to be able to use IDE support in intelisense, type checking, unit testing etc.

Now, there is a question, at which version should we get them. In runtime the version is pretty unpredictable (which is the problem on its own, but not the point here). Recently we came to a conclusion, to use the lowest version, shipped with the lowest supported version of WP & WC. Now, matching WP/WC -> WC-admin -> `*/components` version is another problem. Which so far requires lots of manual labor to dig through `package.json`s in git history.

Every time we bump the min version of WP or WC in my understanding, we should re-do all the above.

Some time ago, I made this PR, to make it a tad easier just for WP https://github.com/WordPress/gutenberg/pull/36005

But there is no such script that updates Woo packages.

Now, to fully automate bumping version, we have to automate all the things around DEWP.

----

That's said, it would still be cool to have at least a part of that automated.

**Comment by tomalec** [comment]
> I think I'm having some gaps in understanding the difference between externalized dependencies with DEWP and other dependencies like could be @woocommerce/navigation???
I hope the comment [above](https://github.com/woocommerce/google-listings-and-ads/pull/1110#issuecomment-983868568), and link to https://github.com/WordPress/gutenberg/issues/35630 helps to clarify that.

> `npm config set save-exact true` could work as well.

My idea was to use `save-exact` only for externalized, and regular ranges for bundled ones.

> Also, I don't understand why "@woocommerce/date": "^3.1.0" is with ^ and then "@woocommerce/navigation": "6.1.0" without it.

As `/date` is bundled and `/navigation` is externalized.

**Comment by tomalec** [comment]
> I'm getting Waiting for testing environment after starting my e2e , but I guess is not well configured on my side. Will check asap.

Have `npm run docker:up` run successfully?

**Comment by tomalec** [comment]
To answer, the offline discussion on DEWP
>  Who cares about `save-exact` if its going to be overrided, or if is not, why have one exact and other not?

This is definitely a valid point. I'm still not sure if `save-exact` is a good idea. Preferably, I'd simply add a code comment in `package.json`. What I try to deliver by having "one exact and other not", is to provide some information that those packages versions are bound to WP/WC version not up to us.

Ideally, we'd use [dist-tags](https://github.com/WordPress/gutenberg/issues/24376), and store it like:
```
		"@woocommerce/navigation": "wc-5.6",
		"classnames": "^2.3.1",
```

**Comment by puntope** [comment]
> Have `npm run docker:up` run successfully?

I got 

```
WordPress 5.8.2
PHP 7.4.26
MariaDB 10.7.1
Initializing /Users/miguelperezpellicer/Sites/wp-test/wordpress/wp-content/plugins/google-listings-and-ads/tests/e2e/docker/initialize.sh
key cannot contain a space
Docker exit code: 15
```

**Comment by puntope** [comment]
✅  Visual testing looks good for me overall. I went all over the Onboarding and saw how the products started to sync afterwards

**Comment by puntope** [comment]
> > Have `npm run docker:up` run successfully?

Following -> p1633080643456400-slack-C01BWDDTGKX

Seems like I was not the only one having it... I'm on it

**Comment by puntope** [comment]
Except the broken test here --> https://github.com/woocommerce/google-listings-and-ads/issues/1129

All them pass so, I guess this is good to go ✅ 

I will try to discover why that 2 tests didn't pass. But it's a separated issue.

**Review by puntope — APPROVED** [review]

**Pull request merged**
