### PR TITLE
Clear product stats cache on every product sync 

### PR DESCRIPTION
**Pull request by nima-karimi**
### Changes proposed in this Pull Request:

This PR adds a new event to ~refresh~ clear the product stats cache on every successful product sync attempt. It hooks into the `woocommerce_gla_batch_updated_products` and `woocommerce_gla_batch_deleted_products` events and clears the cache used to store product feed statistics.

### Detailed test instructions:

1. Create a new product and sync it
2. The stats displayed on the `Product feed` tab must be updated to reflect this new synced product

### Changelog Note:

> Fix - Clear product stats cache on every successful sync

### CODE REVIEW

**Review by layoutd — COMMENTED** [review]
This works as intended, but at the moment, doesn't change any numbers because the product stats uses `find_sync_pending_product_ids` to find NOT_SYNCED products:
https://github.com/woocommerce/google-listings-and-ads/blob/ddc65eeea24e8e0a726d8ba49b705338fea90eeb/src/MerchantCenter/MerchantStatuses.php#L503-L505

This only shows products that are visible and not-yet-sent to Merchant Center. However, if a new valid product is added, it will be visible and already sent to Merchant Center, but not yet available in the `productstatuses` API, so it wouldn't show up in any of the stats categories. A separate PR for a `not_synced` product search is incoming.

**Comment by nima-karimi** [comment]
@layoutd I think this can be review again and possibly merged now that https://github.com/woocommerce/google-listings-and-ads/pull/756 is merged. 

I'm just not sure how it would affect the site's performance since the stats refresh functionality is still slow. Maybe we need to wait until https://github.com/woocommerce/google-listings-and-ads/pull/769 is merged too?

**Comment by mikkamp** [comment]
Just wanted to add my 2cents on this issue. Refreshing the stats data right away after batch update/delete seems premature, because Google takes a while to process the product data. While it's usually updated after a couple minutes they do mention: 
> Product data can take up to 30 minutes to update

Wouldn't it make more sense to just clear the transient after batch update/delete? That way the next time the UI requests the data it will try to get fresh data (instead of waiting for the full hour to pass).

**Comment by nima-karimi** [comment]
> Just wanted to add my 2cents on this issue. Refreshing the stats data right away after batch update/delete seems premature, because Google takes a while to process the product data. While it's usually updated after a couple minutes they do mention:
> 
> > Product data can take up to 30 minutes to update
> 
> Wouldn't it make more sense to just clear the transient after batch update/delete? That way the next time the UI requests the data it will try to get fresh data (instead of waiting for the full hour to pass).

Hmm yeah, that sounds better. Do we store the issues in a transient or it's in a DB table? Not sure if we have a method to delete all cache 🤔 cc: @layoutd

**Comment by nima-karimi** [comment]
nvm seems like this transient is used for the cache: `Transients::MC_STATUSES`

**Comment by layoutd** [comment]
> Do we store the issues in a transient or it's in a DB table? Not sure if we have a method to delete all cache 🤔 
> nvm seems like this transient is used for the cache: `Transients::MC_STATUSES`

Too fast for me! Account/product Issues are stored in the `wp_gla_merchant_issues` table, and the product statistics are stored in the `_gla_mc_statuses` transient. However, all requests for product statistics, issues or feed information _are_ dependent on a valid `MC_STATUSES` transient. So deleting that would force everything to be refreshed on the next visit to the Product Feed page.

Update to add that we do exactly that to clear the cache in Connection Test:
https://github.com/woocommerce/google-listings-and-ads/blob/df4fa30bb8063b0e3a0967850c94e59578ce38cd/src/ConnectionTest.php#L844-L847

**Comment by nima-karimi** [comment]
Changed this event to only clear the cache. @layoutd Ready for another review 🙏

**Review by layoutd — APPROVED** [review]
💯  This looks good and is working.

> The stats displayed on the Product feed tab must be updated to reflect this new synced product

I just wanted to point out here that the stats will still depend in some cases on the Shopping API reporting a product as synced/not synced (#769 should also help here a bit as deleted products will no longer be included in the stats, although new products will still be at the mercy of the Merchant Center delay).

**Pull request merged**
